;-----------------------------------------------------------------------|
; The MARTIN MAC 300 MODE 1, 9 DMX channels                            |
;-----------------------------------------------------------------------|
; History  :-                                                           |
;-----------------------------------------------------------------------|
; Revision |  Date     |  By    | Description                           |
;----------|-----------|--------|---------------------------------------|
; 1.0      |  20-07-01 | Edward | Created from Mode 2                   |
;-----------------------------------------------------------------------|

DEVICE=MMac300m1                ; Device Name (upto 11 chars after '='
DEVICE23=9-Channels            ; 22 chars after '='
       				; extra information for softkey prompt lines 2&3
                        	; a total of 22 chars, split into 2 lines of 11

; Device information
;                                  __ Number of lines of DMX info.
;                                 |  __ Number of lines of wheel info
;                                 | |
;                                 | |
;                                 | |
HSTART 3 11 1b05 438 305 ff 0 2   9 10
;      |  |  |    |   |  |  | |
;      |  |  |    |   |  |  | |__ Line number for flash button DMX info
;      |  |  |    |   |  |  |      from DMX definition (1..x)
;      |  |  |    |   |  |  |__ Button release value
;      |  |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;      |  |  |    |   |__ The TILT arc in Degrees
;      |  |  |    |__ The Pan arc in degrees
;      |  |  |__ Date in PC format (1b05==5/08/93)
;      |  |__ Number of DMX slots used
;      |__ Patch direction (1-backward, 0 forward, (3 for moving head, 1 for Moving Mirror))



TEXTSTART          ; Upto 21 lines of 28 characters (use the template below)
                               ;
 MARTIN MAC 300                ;
                               ;
     MODE 1                    ;
                               ;
 9-DMX CHANNELS               ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART                          ; DMX defintion
1  2 40 0 24 0      ; SHUTTER
2  1  0 0  0 0      ; DIMMER
3  2  0 0  8 0      ; CYAN
4  2  0 0  7 0      ; MAGENTA
5  2  0 0  9 0      ; YELLOW
6  2 40 0 38 0      ; COLOR WHEEL
7  2  0 0 40 0      ; FROST
8  2 20 0 13 0      ; PAN
9  2 20 0 14 0      ; TILT
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|_ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition

WSTART
8 ffff 2323 1  24 0  7   0 1  0  1  0  0  0  0  0  ; 1. SHUTTER
8 ffff ffff 4   0 0  8   0 1  1  2  0  0  0  0  0  ; 2. DIMMER
8 ffff    0 1   8 0 10   0 1  2  3  0  0  0  0  0  ; 3. CYAN
8 ffff    0 1   7 0 11   0 1  3  4  0  0  0  0  0  ; 4. MAGENTA
8 ffff    0 1   9 0 12   0 1  4  5  0  0  0  0  0  ; 5. YELLOW
8 ffff    0 1  38 0  1   0 1  5  6  0  0  0  0  0  ; 6. COLOR WHEEL
8 ffff    0 1  40 0 25   0 1  6  7  0  0  0  0  0  ; 7. FROST
6 ffff 8000 3  13 0  5   0 1  7  8  0  0  0  0  0  ; 8. PAN
6 ffff 8000 3  14 0  6   0 1  8  9  0  0  0  0  0  ; 9. TILT
8 ffff    0 2 103 0  2 103 3  2  3  5  4  0  0  0  ;10. LEE
;|   |    | |   | |  |   | |  |  |  |  |  |  |  |__ List of Table channels as
;|   |    | |   | |  |   | |  |  |_______________ line numbers from DMX def.
;|   |    | |   | |  |   | |  |                   0 means unused channel
;|   |    | |   | |  |   | |  |__ DMX line (minus 1) pertainig to this wheel
;|   |    | |   | |  |   | |__ Number of chanels under control OR Table width
;|   |    | |   | |  |   |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |   | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |   | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |   |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   | _ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;    eg. for 8 bit channels it is 8, for 12 bit channels it is 4

;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between

TSTART 3 103
lee101                  33      243     118
lee102                  25      232     133
lee103                  6       143     108
lee104                  60      250     155
lee105                  2       251     214
lee106                  91      247     247
lee107                  24      178     178
lee108                  164     220     220
lee109                  22      161     176
lee110                  0       95      166
lee111                  0       131     213
lee113                  55      194     254
lee115                  195     145     11
lee116                  248     172     11
lee117                  47      45      4
lee118                  226     127     106
lee119                  247     34      144
lee120                  237     93      230
lee121                  99      233     18
lee122                  153     231     38
lee124                  226     241     131
lee126                  146     138     242
lee127                  94      210     224
lee128                  64      152     248
lee129                  255     255     255
lee130                  255     255     255
lee131                  149     149     45
lee132                  221     59      83
lee134                  42      227     181
lee135                  109     248     238
lee136                  42      111     136
lee137                  56      5       108
lee138                  28      155     41
lee139                  255     255     255
lee140                  118     95      14
lee141                  226     92      63
lee142                  95      41      118
lee143                  189     113     132
lee144                  147     88      15
lee145                  255     255     255
lee147                  0       204     169
lee148                  255     255     255
lee151                  15      149     149
lee152                  15      149     141
lee153                  15      149     160
lee154                  15      141     144
lee156                  26      163     158
lee158                  16      249     221
lee159                  13      123     109
lee161                  118     25      58
lee162                  16      152     122
lee164                  30      240     246
lee165                  145     43      54
lee166                  255     255     255
lee169                  38      107     113
lee170                  59      73      156
lee172                  217     136     0
lee174                  78      30      62
lee176                  7       162     175
lee179                  70      246     202
lee180                  158     41      200
lee181                  247     119     238
lee182                  92      251     248
lee183                  255     255     255
lee184                  3       127     112
lee185                  6       104     109
lee186                  6       114     122
lee187                  6       131     122
lee188                  6       135     121
lee189                  31      112     104
lee190                  55      112     104
lee191                  55      136     112
*** TEND ***

MACRO "LAMP ON" 1 1
50 e6
1  23
MEND

MACRO "RESET" 2  1
50 d5
1  0
MEND

MACRO "LAMP OFF" 3 1 3 4 5
60 ff e7 e7 e7 
1  0   0  0  0
MEND

;--------------------------------------------------------------------


