;-----------------------------------------------------------------------|
; The FutureLight Mh640               Personality for the Diamond II    | 
;-----------------------------------------------------------------------|
;       History :-                                                      |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;       1.0  | 31-07-01  | Edward | Created from Peral                  |
;---------------------------------------------------------------------- |


DEVICE=FL_MH-840               ; Device Name (upto 11 chars after '='
DEVICE23=16 Channels              ; 22 chars after '='
			          ; extra information for softkey prompt lines 2&3
						; a total of 22 chars, split into 2 lines of 11

; Device information
;                                   __ Number of lines of DMX info.
;                                  |   __ Number of lines of wheel info
;                                  |  |
;                                  |  |
;                                  |  |
HSTART   3 16 1b05 530 280 ff 0  9 16 14
;        |  |  |    |   |  |  |  |
;        |  |  |    |   |  |  |  |__ Line number for flash button DMX info
;        |  |  |    |   |  |  |      from DMX definition (1..x)
;        |  |  |    |   |  |  |__ Button release value
;        |  |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;        |  |  |    |   |__ The TILT arc in Degrees
;        |  |  |    |__ The Pan arc in degrees
;        |  |  |__ Date in PC format (1b05==5/08/93)
;        |  |__ Number of DMX slots used
;        |__ (1-mirror, 3-for moving head)


TEXTSTART               ; Upto 21 lines of 28 characters (use the template)
                            ;
                            ;
    FUTURELIGHT MH-840      ;
                            ;
      16 DMX Channels       ; 
                            ;
                            ;
TEXTEND
;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART                          ; DMX defintion
1  2 20 0  13 0      ; PAN
2  0  0 0   0 0      ; PAN LOW
3  2 20 0  14 0      ; TILT
4  0  0 0   0 0      ; TILT LOW
5  2 40 0  58 0      ; SPEED P/T
6  2 40 0  52 0      ; CONTROL
7  2 40 0  38 0      ; COLOR
8  2 80 0   8 0      ; CYAN
9  2 80 0   7 0      ; MAGENTA
10 2 80 0   9 0      ; YELLOW
11 2 40 0  59 0      ; SPEED CMY
12 2 40 0 107 0      ; COLOUR MACRO
13 2 40 0  51 0      ; EFFECT
14 2  0 0  43 0      ; ZOOM
15 2  0 0  24 0      ; SHUTTER
16 1  0 0   0 0      ; DIMMER
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition

WSTART
4 ffff 8080 3 13 1  5  0 1  0  1  0  0  0  0  0  ; 1. PAN
4 ffff 8080 3 14 1  6  0 1  2  3  0  0  0  0  0  ; 2. TILT
8 ffff    0 1 25 0 41  0 1  4  5  0  0  0  0  0  ; 3. SPEED P/T
8 ffff    0 1 52 0 43  0 1  5  6  0  0  0  0  0  ; 4. CONTROL
8 ffff    0 1 38 0  9  0 1  6  7  0  0  0  0  0  ; 5. COLOR
8 ffff ffff 1  8 0 10  0 1  7  8  0  0  0  0  0  ; 6. CYAN
8 ffff ffff 1  7 0 11  0 1  8  9  0  0  0  0  0  ; 7. MAGENTA
8 ffff ffff 1  9 0 12  0 1  9 10  0  0  0  0  0  ; 8. YELLOW
8 ffff    0 1 59 0 42  0 1 10 11  0  0  0  0  0  ; 9. SPEED CMY
8 ffff    0 1 107 0 15 0 1 11 12  0  0  0  0  0  ; 10. COLOUR MACROS
8 ffff    0 1 51 0  25  0 1 12 13  0  0  0  0  0  ; 11. EFFECT
8 ffff 4646 1 43 0  1  0 1 13 14  0  0  0  0  0  ; 12. ZOOM
8 ffff    0 1 24 0  7  0 1 14 15  0  0  0  0  0  ; 13. SHUTTER
8 ffff 8c8c 4  0 0  8  0 1 15 16  0  0  0  0  0  ; 14. DIMMER
8 ffff    0 2  4 0  3  4 5  6  7 12  8 10  9  0  ; 15. COLOR TABLE
;|   |    | |  | |  |  | |  |  |  |  |  |  |  |__ List of Table channels as 
;|   |    | |  | |  |  | |  |  |_______________ line numbers from DMX def.
;|   |    | |  | |  |  | |  |                   0 means unused channel
;|   |    | |  | |  |  | |  |__ DMX line (minus 1) pertainig to this wheel
;|   |    | |  | |  |  | |__ Number of chanels under control OR Table width
;|   |    | |  | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |  | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |  | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |  |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between


TSTART 5 4
Open              0  0  255 255  255
Red               0  0  255   0    0
Amber             0  0  255   0   30
Yellow            0  0  255   0  255
Green             0  0    0   0  255
Cyan              0  0    0 255  255
Blue              0  0    0 255  100
Lavender          0  0  205 255   55
UV                0  0    0 155    0
Magenta           0  0  255 255    0
*** TEND ***

; Macros
MACRO "LAMP ON" 1   6   
30   85
MEND

MACRO "RESET" 2    6
30   85
MEND

MACRO "LAMP OFF" 3    6
50   eb
MEND

MACRO "FAN MAX" 4    6
0   0
MEND

MACRO "FAN MIN" 5    6
0   7f
MEND
