;-----------------------------------------------------------------------|
; The Syncrolite wash         Personality for the Diamond II            |
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;   1.0      |  06-08-01 | Edward | Created from Pearl                  |
;---------------------------------------------------------------------- |


DEVICE=SyncBmWash                  ; Device Name (upto 11 chars after '='
DEVICE23=                          ; 22 chars after '='
				   ; extra information for softkey prompt lines 2&3
			           ; a total of 22 chars, split into 2 lines of 11

; Device information
;				   __ Number of lines of DMX info.
;				  |   __ Number of lines of wheel info
;				  |  |
;				  |  |
HSTART   1 7 1b05 360 270 ff 0 6  7  6
;	 | |  |    |   |  |  |  |
;	 | |  |    |   |  |  |  |__ Line number for flash button DMX info
;	 | |  |    |   |  |  |      from DMX definition (1..x)
;	 | |  |    |   |  |  |__ Button release value
;	 | |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;	 | |  |    |   |__ The TILT arc in Degrees
;	 | |  |    |__ The Pan arc in degrees
;	 | |  |__ Date in PC format (1b05==5/08/93)
;	 | |__ Number of DMX slots used
;	 |__ Patch direction (1-backward, 0 forward, 2 for moving head);


TEXTSTART            ; Upto 21 lines of 28 characters (use the template below)
                            ;  
   SYNCROLITE Wash          ;
                            ; 
                            ;
TEXTEND

;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition



DSTART              ; DMX defintion
1  2 20 0  13 0      ; PAN
2  0  0 0   0 0      ; PAN low
3  2 20 0  14 0      ; TILT
4  0  0 0   0 0      ; TILT low 
5  2  0 0  12 0      ; Focus
6  1  0 0   0 0      ; DIMMER
7  2 40 0  38 0      ; Colour
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately);
;

;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition

WSTART
8 ffff 8080 3  13 1  5  0 1  0  1  0  0  0  0  0  ; 1. PAN
8 ffff 8080 3  14 2  6  0 1  2  3  0  0  0  0  0  ; 2. TILT
8 ffff    0 1  12 0  2  0 1  4  5  0  0  0  0  0  ; 3. Focus
8 ffff ffff 4   0 0  8  0 1  5  6  0  0  0  0  0  ; 4. DIMMER
8 ffff    0 1  38 0  4  0 1  6  7  0  0  0  0  0  ; 5. COLOR
8 ffff    0 2   4 0  1  4 1  6  7  0  0  0  0  0  ; 6. COLOR table
;|    |    | |  | |  |  | |  |  |  |  |  |  |  |__ List of Table channels as 
;|    |    | |  | |  |  | |  |  |_______________ line numbers from DMX def.
;|    |    | |  | |  |  | |  |                   0 means unused channel
;|    |    | |  | |  |  | |  |__ DMX line (minus 1) pertainig to this wheel
;|    |    | |  | |  |  | |__ Number of chanels under control OR Table width
;|    |    | |  | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|    |    | |  | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|    |    | |  | |__ 0 for 8 bits, 1 for 16 bits
;|    |    | |  |__  Attribute name from above list (0..MAX)
;|    |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|    |    |__ Default value (left shifted as necessary)
;|    |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between

TSTART 1 4
Col 1                0
Col 2               40
Col 3               64
Col 4               88
Col 5               96
Col 6              120
Col 7              144
Col 8              168
Col 9              192
Col 10             216
*** TEND ***

