;-----------------------------------------------------------------------|
; RObe Spot 160 Mode 1 personality for the Diamond II                   |
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By       | Description                      |
;------------|-----------|-----------|----------------------------------|
;   1.0      |  26-07-02 | D.Shelton | Created from Pearl               |
;            |  21-01-05 | Phil      | Changed naming to standard       |
;---------------------------------------------------------------------- |


DEVICE=RO_SP160XT        ; Device Name (upto 11 chars) must be enclosed in single
DEVICE23=               ; 22 chars after '='
                        ; extra information for softkey prompt lines 2&3
                        ; a total of 22 chars, split into 2 lines of 11

;                                  __ Number of lines of DMX info.
;                                 |   __ Number of lines of wheel info
;                                 |  |
;                                 |  |
;                                 |  |
HSTART  3  9 1b05 530 285 ff 0 8  9  7
;       |  |  |    |   |  |  | |
;       |  |  |    |   |  |  | |__ Line number for flash button DMX info
;       |  |  |    |   |  |  |     from DMX definition (1..x)
;       |  |  |    |   |  |  |__ Button release value
;       |  |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;       |  |  |    |   |__ The TILT arc in Degrees
;       |  |  |    |__ The Pan arc in degrees
;       |  |  |__ Date in PC format (1b05==5/08/93)
;       |  |__ Number of DMX slots used
;       |__ Patch direction (1-backward, 2 forward)




TEXTSTART       ; Upto 21 lines of 28 characters
                            ;
   Robe Spot 160 Mode 1     ;
       PERSONALITY          ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART              ; DMX Picture
1  2  0 0  13 0      ; PAN
2  0 20 0   0 0      ; PAN low
3  2  0 0  14 0      ; TILT
4  0 20 0   0 0      ; TILT low
5  2 40 0  58 0      ; PT Speed
6  2 40 0  38 0      ; Colour
7  2 40 0  11 0      ; RotGobo
8  2 40 0  64 0      ; GoboSpin 
9  1  0 0  24 0      ; SHUTTER
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information

WSTART
8 ffff 8080 3  13 0  5  0  1 0  1  0  0  0  0  0      ; 1. PAN
8 ffff 8080 3  14 0  6  0  1 2  3  0  0  0  0  0      ; 2. TILT
8 ffff    0 1  58 0 43  0  1 4  5  0  0  0  0  0      ; 3. PT Speed
8 ffff    0 1  38 0  9  0  1 5  6  0  0  0  0  0      ; 4. Colour
8 ffff    0 1  11 0 18  0  1 6  7  0  0  0  0  0      ; 5. RotGobo
8 ffff    0 1  64 0 24  0  1 7  8  0  0  0  0  0      ; 6. GoboSpin
8 ffff 4040 1  24 0  7  0  1 8  9  0  0  0  0  0      ; 7. Shutter
;|   |    | |  | |  |  |  |  |  |  |  |  |  |  |__ List of Table channels as
;|   |    | |  | |  |  |  |  |  |_______________ line numbers from DMX def.
;|   |    | |  | |  |  |  |  |                  ff or 0 means unused channel
;|   |    | |  | |  |  |  |  |__ DMX line pertainnig to this wheel (-1)
;|   |    | |  | |  |  |  |__ Number of chanels under control (Table width)
;|   |    | |  | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |  | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |  | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |  |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tile, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;    eg. for 8 bit channels it is 8, for 12 bit channels it is 4




;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between


; Macros
MACRO "RESET" 1    9
60   85
1    0
MEND
;--------------------------------------------------------------------



