;-----------------------------------------------------------------------|
; The American DJ Matrix Personality for the Diamond II             | 
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;   1.0      |  27-07-01 | Edward | Created from Pearl                  |
;---------------------------------------------------------------------- |


DEVICE=ADJ_Matrix                  ; Device Name (upto 11 chars after '='
DEVICE23=16 Channels                ; 22 chars after '='
				    ; extra information for softkey prompt lines 2&3
				    ; a total of 22 chars, split into 2 lines of 11

; Device information
;				   __ Number of lines of DMX info.
;				  |   __ Number of lines of wheel info
;				  |  |
;				  |  |
;				  |  |
HSTART  2 16 1b05 150 110 ff 0 9  16 16
;	| |  |    |   |  |  | |
; 	| |  |    |   |  |  | |__ Line number for flash button DMX info
;	| |  |    |   |  |  |     from DMX definition (1..x)
;	| |  |    |   |  |  |__ Button release value
;	| |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;	| |  |    |   |__ The TILT arc in Degrees
;	| |  |    |__ The Pan arc in degrees
;	| |  |__ Date in PC format (1b05==5/08/93)
;	| |__ Number of DMX slots used
;	|__ Patch direction (bit 0:1-backward, 0 forward, bit 1:1 moving head


TEXTSTART       ; Upto 21 lines of 28 characters (use the template below)
                                     ;
        AMERICAN DJ                  ; 
          Matrix                  ;
                                     ;
        16 CHANNELS                  ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART              ; DMX defintion
1  2  0 0   0 0      ; DIM1
2  2  0 0   0 0      ; DIM2
3  2  0 0   0 0      ; DIM3
4  2  0 0   0 0      ; DIM4
5  2  0 0   0 0      ; DIM5
6  2  0 0   0 0      ; DIM6
7  2  0 0   0 0      ; DIM7
8  2  0 0   0 0      ; DIM8
9  2  0 0   0 0      ; DIM9
10 2  0 0   0 0      ; DIM10
11 2  0 0   0 0      ; DIM11
12 2  0 0   0 0      ; DIM12
13 2  0 0   0 0      ; DIM13
14 2  0 0   0 0      ; DIM14
15 2  0 0   0 0      ; DIM15
16 2  0 0   0 0      ; DIM16
;| |  | |   | |
;| |  | |   | |__ Spare (always 0 for now)
;| |  | |   |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)
;
;
;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition

WSTART
8  ffff ffff 1  0 0  1  0 1  0  1  0  0  0  0  0  ; 1. DIM1
8  ffff ffff 1  0 0  2  0 1  1  2  0  0  0  0  0  ; 2. DIM2
8  ffff ffff 1  0 0  3  0 1  2  3  0  0  0  0  0  ; 3. DIM3
8  ffff ffff 1  0 0  4  0 1  3  4  0  0  0  0  0  ; 4. DIM4
8  ffff ffff 1  0 0  5  0 1  4  5  0  0  0  0  0  ; 5. DIM5
8  ffff ffff 1  0 0  6  0 1  5  6  0  0  0  0  0  ; 6. DIM6
8  ffff ffff 1  0 0  7  0 1  6  7  0  0  0  0  0  ; 7. DIM7
8  ffff ffff 1  0 0  8  0 1  7  8  0  0  0  0  0  ; 8. DIM8
8  ffff ffff 1  0 0  9  0 1  8  9  0  0  0  0  0  ; 9. DIM9
8  ffff ffff 1  0 0 10  0 1  9 10  0  0  0  0  0  ; 10. DIM10
8  ffff ffff 1  0 0 11  0 1 10 11  0  0  0  0  0  ; 11. DIM11
8  ffff ffff 1  0 0 12  0 1 11 12  0  0  0  0  0  ; 12. DIM12
8  ffff ffff 1  0 0 13  0 1 12 13  0  0  0  0  0  ; 13. DIM13
8  ffff ffff 1  0 0 14  0 1 13 14  0  0  0  0  0  ; 14. DIM14
8  ffff ffff 1  0 0 15  0 1 14 15  0  0  0  0  0  ; 15. DIM15
8  ffff ffff 1  0 0 16  0 1 15 16  0  0  0  0  0  ; 16. DIM16
;|    |    | |  | |  |  | |  |  |  |  |  |  |  |__ List of Table channels as 
;|    |    | |  | |  |  | |  |  |_______________ line numbers from DMX def.
;|    |    | |  | |  |  | |  |                  ff or 0 means unused channel
;|    |    | |  | |  |  | |  |__ DMX line pertainnig to this wheel (-1)
;|    |    | |  | |  |  | |__ Number of chanels under control (Table width)
;|    |    | |  | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|    |    | |  | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|    |    | |  | |__ 0 for 8 bits, 1 for 16 bits
;|    |    | |  |__  Attribute name from above list (0..MAX)
;|    |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|    |    |__ Default value (left shifted as necessary)
;|    |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between
;--------------------------------------------------------------------


MACRO "Beams FULL" 1 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 
1 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
MEND

MACRO "Beams Half" 2 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 
1 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 
MEND

MACRO "Beams OFF" 3 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 
1 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
MEND

