;-----------------------------------------------------------------------|
; The CYBERLIGHT Personality for the Diamond II                         | 
;-----------------------------------------------------------------------|
;       History :-                                                      |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;       1.0  |  03-06-94 |  Anwar | Created                             |
;       1.1  |  18-11-94 |  jb    | tables added                        |
;       1.2  |  24-10-95 |  Anwar | Control channel default now 0       |
;            |  08-08-01 |  Edward| Revised for Mode 2 from Pearl       |     
;---------------------------------------------------------------------- |


DEVICE=HE_Cyber2              ; Device Name (upto 11 chars after '='
DEVICE23=                     ; 22 chars after '='
			      ; extra information for softkey prompt lines 2&3
			      ; a total of 22 chars, split into 2 lines of 11

; Device information
;                                   __ Number of lines of DMX info.
;                                  |   __ Number of lines of wheel info
;                                  |  |
;                                  |  |
;                                  |  |
HSTART  1 20 1b05 170 108 ff 0 18 20 24
;        | |  |    |   |  |  |  |
;        | |  |    |   |  |  |  |__ Line number for flash button DMX info
;        | |  |    |   |  |  |      from DMX definition (1..x)
;        | |  |    |   |  |  |__ Button release value
;        | |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;        | |  |    |   |__ The TILT arc in Degrees
;        | |  |    |__ The Pan arc in degrees
;        | |  |__ Date in PC format (1b05==5/08/93)
;        | |__ Number of DMX slots used
;        |__ Patch direction (1-backward, 0 forward, 2 for moving head)


TEXTSTART               ; Upto 21 lines of 28 characters (use the template)
                            ;
                            ;
   Cyber light              ;
   personality              ;
			    ;
   mode=2                   ;
                               ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART                          ; DMX defintion
1  2 20 0 13 0      ; PAN
2  0  0 0  0 0      ; Dummy for 16-bit channels 
3  2 20 0 14 0      ; TILT
4  0  0 0  0 0      ; Dummy for 16-bit channels 
5  2 40 0 38 0      ; COLOR WHEEL
6  2  0 0  8 0      ; CYAN
7  2  0 0  7 0      ; MAGENTA
8  2  0 0  9 0      ; YELLOW
9  2 40 0 36 0      ; GOBO1
10 2 40 0 37 0      ; GOBO2
11 2 40 0 49 0      ; GOBO MODE
12 2  0 0 43 0      ; ZOOM
13 2  0 0 12 0      ; FOCUS
14 2  0 0 15 0      ; IRIS
15 2 40 0 51 0      ; EFFECT
16 2 40 0 40 0      ; FROST
17 2  0 0 24 0      ; SHUTTER
18 1  0 0  0 0      ; DIMMER
19 2  0 0 25 0      ; SPEED
20 2 40 0 52 0      ; CONTROL
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition


WSTART
8 ffff ffff 1  15 0  1   0 1 13 14  0  0  0  0  0  ; 1. IRIS
8 ffff 8080 1  12 0  2   0 1 12 13  0  0  0  0  0  ; 2. FOCUS
6 ffff 8000 3  13 1  5   0 1  0  1  0  0  0  0  0  ; 3. PAN
6 ffff 8000 3  14 1  6   0 1  2  3  0  0  0  0  0  ; 4. TILT
8 ffff    0 1  43 0  7   0 1 11 12  0  0  0  0  0  ; 5. ZOOM
8 ffff ffff 4   0 0  8   0 1 17 18  0  0  0  0  0  ; 6. DIMMER
8 ffff    0 1  38 0  4   0 1  4  5  0  0  0  0  0  ; 7. COLOR WHEEL
8 ffff ffff 1   8 0 10   0 1  5  6  0  0  0  0  0  ; 8. CYAN
8 ffff ffff 1   7 0 11   0 1  6  7  0  0  0  0  0  ; 9. MAGENTA
8 ffff ffff 1   9 0 12   0 1  7  8  0  0  0  0  0  ; 10. YELLOW
8 ffff    0 1  36 0 17   0 1  8  9  0  0  0  0  0  ; 11. GOBO1
8 ffff 8080 1  12 0 18   0 1 12 13  0  0  0  0  0  ; 12. FOCUS
8 ffff    0 1  37 0 19   0 1  9 10  0  0  0  0  0  ; 13. GOBO2
8 ffff    0 1  49 0 20   0 1 10 11  0  0  0  0  0  ; 14. GOBO MODE
8 ffff    0 1  51 0 25   0 1 14 15  0  0  0  0  0  ; 15. EFFECT
8 ffff ffff 1  40 0 26   0 1 15 16  0  0  0  0  0  ; 16. FROST
8 ffff ffff 1  24 0 27   0 1 16 17  0  0  0  0  0  ; 17. SHUTTER
8 ffff    0 1  25 0 28   0 1 18 19  0  0  0  0  0  ; 18. SPEED
8 ffff    0 1  52 0 41   0 1 19 20  0  0  0  0  0  ; 19. CONTROL
8 ffff ffff 2 103 0  3 103 3  5  6  8  7  0  0  0  ; 20. LEE
8 ffff    0 2   4 0 33   4 1  4  5  0  0  0  0  0  ; 21. COLOR 
8 ffff    0 2  11 0 34  11 1  8  9  0  0  0  0  0  ; 22. Static Gobo table
8 ffff    0 2  64 0 35  64 1  9 10  0  0  0  0  0  ; 23. Rotating Gobo Table
8 ffff    0 2  51 0 36  51 1 14 15  0  0  0  0  0  ; 24. Effects Table
;|    |   | |   | |  |  |  |  |  |  |  |  |  |  |__ List of Table channels as 
;|    |   | |   | |  |  |  |  |  |_______________ line numbers from DMX def.
;|    |   | |   | |  |  |  |  |                   0 means unused channel
;|    |   | |   | |  |  |  |  |__ DMX line (minus 1) pertainig to this wheel
;|    |   | |   | |  |  |  |__ Number of chanels under control OR Table width
;|    |   | |   | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|    |   | |   | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|    |   | |   | |__ 0 for 8 bits, 1 for 16 bits
;|    |   | |   |__  Attribute name from above list (0..MAX)
;|    |   | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|    |   |__ Default value (left shifted as necessary)
;|    |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between



; LEE TABLE
TSTART     3    103
lee101                	228	0      	216
lee102                	16      1       160
lee103                 	255    	134     176
lee104                 	186    	14      130
lee105                 	193    	193     100
lee106                 	172    	1       4
lee107                 	250    	135     128
lee108                 	94     	44      52
lee109                 	236  	120     134
lee110                 	173    	1       120
lee111                 	229    	102     105
lee113                 	212    	94     	1
lee115                 	94     	104    	237
lee116                 	50     	108    	236
lee117                 	156    	139    	254
lee118                 	94     	138    	222
lee119                 	64     	232    	116
lee120                 	1      	221    	89
lee121                 	128    	89     	184
lee122                 	110    	86     	193
lee124                 	83     	82     	206
lee126                 	210    	186    	51
lee127                 	103    	96     	95
lee128                 	155    	107    	81
lee129                 	0      	0      	0
lee130                 	0      	0      	0
lee131                 	112    	106    	210
lee132                 	2      	230    	167
lee134                 	125    	84     	110
lee135                 	203    	6      	79
lee136                 	252    	149    	155
lee137                 	178    	249    	150
lee138                 	227    	105    	214
lee139                 	0      	0      	0
lee140                 	141    	138    	255
lee141                 	70     	153    	233
lee142                 	145    	209    	142
lee143                 	114    	147    	234
lee144                 	117    	141    	243
lee145                 	0      	0      	0
lee147                 	213    	93     	123
lee148                 	146    	83     	48
lee151                 	254    	117    	134
lee152                 	254    	117    	147
lee153                 	254    	117    	134
lee154                 	254    	126    	152
lee156                 	249    	99     	123
lee158                 	246    	34     	100
lee159                 	216    	126    	168
lee161                 	140    	231    	218
lee162                 	240    	111    	144
lee164                 	165    	71     	71
lee165                 	123    	212    	248
lee166                 	0      	0      	0
lee169                 	212    	149    	157
lee170                 	166    	140    	133
lee172                 	88     	123    	252
lee174                 	170    	231    	211
lee176                 	255    	116    	125
lee179                 	170    	0      	112
lee180                 	123    	255    	111
lee181                 	78     	255    	87
lee182                 	236    	4      	4
lee183                 	84     	131    	192
lee184                 	234    	155    	166
lee185                 	249    	141    	157
lee186                 	249    	130    	151
lee187                 	249    	119    	151
lee188                 	187    	126    	153
lee189                 	224    	144    	185
lee190                 	178    	131    	168
lee191                 	178    	121    	159
*** TEND ***

; Static Gobo Table
TSTART 1 11
Gobo1_M             189
Gobo2_M             181
Gobo3_M             173
Gobo4_M             166
Gobo5_M             158
Gobo6_M             150
Gobo7_M             143
Gobo8_M             133
Gobo1_Mshk          186
Gobo2_Mshk          179
Gobo3_Mshk          170
Gobo4_Mshk          163
Gobo5_Mshk          156
Gobo6_Mshk          145
Gobo7_Mshk          138
Gobo8_Mshk          130
->->Fast            127
->->Med              77
->->Slow             66
<-<-Slow             63
<-<-Med              51
<-<-Fast             05
*** TEND ***


; Colour Wheel Table
TSTART 1 4
Col_1_M            189
Col_2_M            181
Col_3_M            173
Col_4_M            166
Col_5_M            158
Col_6_M            150
Col_7_M            143
Col_8_M            133
Col_1_2_M          186
Col_2_3_M          179
Col_3_4_M          170
Col_4_5_M          163
Col_5_6_M          156
Col_6_7_M          145
Col_7_8_M          138
Col_8_1_M          130
->->Fast           127
->->Med             77
->->Slow            66
<-<-Slow            63
<-<-Med             51
<-<-Fast            05
*** TEND ***


; Effects Table 
TSTART 1 51
E1-Open-M           69
E2_Prism_M          20
E3_cymTri_M         36
E4_Yellow_M         54
E5_Magenta_M        84
E6_Wide_M           83
E7_Diff_M          112
E8_Cyan_M          128
*** TEND ***

; Rotating Gobo table 
TSTART 1 64
Gobo1 >> M            99
Gobo2 >> M           107
Gobo3 >> M           117
Gobo4 >> M           128
Gobo1 << M            61
Gobo2 << M            71
Gobo3 << M            82
Gobo4 << M            92
Gobo1<->M             13
Gobo2<->M             26
Gobo3<->M             43
Gobo4<->M             51
*** TEND ***


MACRO "HOME" 1  18  20
20 ff  ff
20  0  ff  
40  0  40
1   0   0
MEND

MACRO "SHUTDOWN" 2  18  20
20 ff  ff
20  0  ff  
40  0  80
1   0   0
MEND

;--------------------------------------------------------------------


