;-----------------------------------------------------------------------
; The LE MAITRE G300 SMOKE MACHINE 2 CHANNEL strobe personality         |
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;   1.0      |  18-11-99 | P.Bari | Created                             |
;-----------------------------------------------------------------------


DEVICE=LMG300Smoke              ; Device name, upto 11 chars after '=')
DEVICE23=2 Channel              ; 22 chars after '='
                                ; extra information for softkey prompt lines 2&3
                                ; a total of 22 chars, split into 2 lines of 11

; Device information
;                                 __ Number of lines of DMX info.
;                                |  __ Number of lines of wheel info
;                                | |
HSTART   1 2 1b05  0   0 ff  0 1 2 2
;        | |  |    |   |  |  | |
;        | |  |    |   |  |  | |__ Line number for flash button DMX info
;        | |  |    |   |  |  |     from DMX definition
;        | |  |    |   |  |  |__ Button release value
;        | |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;        | |  |    |   |__ The TILT arc in Degrees
;        | |  |    |__ The Pan arc in degrees
;        | |  |__ Date in PC format (1b05==5/08/93)
;        | |__ Number of DMX slots used
;        |__ Patch direction (1-backward, 2 forward)


TEXTSTART       ; Upto 21 lines of 28 characters (use the template below)
                                     ;
          LE MAITRE                  ;
      G300 SMOKE MACHINE             ;
                                     ;
         (2 Channel)                 ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
                                     ;
TEXTEND


;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART              ; DMX defintion
1  2  0 0   0 0      ; INTENSITY (LIGHT->HEAVY)
2  1  0 0 134 0      ; ON/OFF
;| |  | |   | |
;| |  | |   | |__ Spare (always 0 for now)
;| |  | |   |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (ask shad)
;| |__ Channel type (1=HTP, 2=LTP)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)
;
;
;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last WHEEL definition

WSTART
8 ffff    0 1   0 0  7  0 1 0 1  0  0  0 0 0      ; INTENSITY (LIGHT->HEAVY)
8 ffff ffff 4 134 0  8  0 1 1 2  0  0  0 0 0      ; ON/OFF
;|   |    | |   | |  |  | | | |  |  |  | | |
;|   |    | |   | |  |  | | | |  |  |  | | |__ List of Table channels as
;|   |    | |   | |  |  | | | |_______________ line numbers from DMX def.
;|   |    | |   | |  |  | | |                  ff or 0 means unused channel
;|   |    | |   | |  |  | | |__ DMX line pertaining to this wheel (-1)
;|   |    | |   | |  |  | |__ Number of chanels under control (Table width)
;|   |    | |   | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |   | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |   | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |   |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tile, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;    eg. for 8 bit channels it is 8, for 12 bit channels it is 4


