;-----------------------------------------------------------------------|
; The Clay Paky Stage Color 300 Personality for the Diamond II          |
;-----------------------------------------------------------------------|
;       History :-                                                      |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;       1.0  |  30-09-98 |Unknown | Created                             |
;---------------------------------------------------------------------- |
;
DEVICE=CPStgCol300           ;Device Name upto 11 chars after '='
DEVICE23=8 Chans            ;22 chars after '='
                            ;Extra information for softkey prompt lines 2&3 
                            ;A total of 22 chars, split into 2 lines of 11
;
; Device information
;                                          __ Number of lines of DMX info.
;                                         |    __ Number of lines of wheel info
;                                         |   |
;                                         |   |
;                                         |   |
HSTART   2   8   0   450 252  ff  0   7   8   9 
;        |   |   |    |   |   |   |   |
;        |   |   |    |   |   |   |   |__ Line number for flash button DMX info
;        |   |   |    |   |   |   |      from DMX definition (1..x)
;        |   |   |    |   |   |   |__ Button release value
;        |   |   |    |   |   |__ Button ON value (ff means use swop/add fader)
;        |   |   |    |   |__ The TILT arc in Degrees
;        |   |   |    |__ The Pan arc in degrees
;        |   |   |__ Date in PC format (1b05==5/08/93)
;        |   |__ Number of DMX slots used
;      |__ Patch direction (1-backward, 0 forward, (3 for moving head, 1 for Moving Mirror))
;
;
;Upto 21 lines of 28 chars (use the template)
TEXTSTART               ; Upto 21 lines of 28 characters (use the template)
                            ;
                            ;
        CLAY PAKY           ;
     STAGE COLOR 300        ;
       PERSONALITY          ;
                            ;
TEXTEND
;------------------------------------------------------------
;
; For the Attribute Dictionary refer to file 'dict.per'
;
;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition
;
DSTART                               ;DMX Definition
   1 2  0 0   8 0          ;Cyan
   2 2  0 0   7 0          ;Magenta
   3 2  0 0   9 0          ;Yellow
   4 2  0 0  17 0          ;Strobe
   5 2 20 0  13 0          ;Pan
   6 2 20 0  14 0          ;Tilt
   7 1  0 0   0 0          ;Dimmer
   8 2  0 0  40 0          ;Frost
;  | |  | |   | |
;  | |  | |   | |__ Spare (always 0 for now)
;  | |  | |   |__ Attribute name (See list above)
;  | |  | |__ Curve (0 means no curve otherwise curve number)
;  | |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;  | |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;  |__ DMX offset (1..255, 0 means DIMMER will be patched seperately)
;
;
;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition
WSTART
 8 ffff ffff 1   8 0  9  0  1  0  1  0  0  0  0  0  ;Cyan
 8 ffff ffff 1   7 0 10  0  1  1  2  0  0  0  0  0  ;Magenta
 8 ffff ffff 1   9 0 12  0  1  2  3  0  0  0  0  0  ;Yellow
 8 ffff ffff 1  17 0  1  0  1  3  4  0  0  0  0  0  ;Strobe
 8 ffff 8080 3  13 0  5  0  1  4  5  0  0  0  0  0  ;Pan
 8 ffff 8080 3  14 0  6  0  1  5  6  0  0  0  0  0  ;Tilt
 8 ffff ffff 4   0 0  8  0  1  6  7  0  0  0  0  0  ;Dimmer
 8 ffff    0 1  40 0  7  0  1  7  8  0  0  0  0  0  ;Frost
 8 ffff ffff 2   4 0  3  4  3  0  1  3  2  0  0  0  ;Color Table
;|    |    | |   | |  |  |  |  |  |  |  |  |  |  |__ List of Table channels as
;|    |    | |   | |  |  |  |  |  |_______________ line numbers from DMX def.
;|    |    | |   | |  |  |  |  |                   0 means unused channel
;|    |    | |   | |  |  |  |  |__ DMX line (minus 1) pertainig to this wheel
;|    |    | |   | |  |  |  |__ Number of chanels under control OR Table width
;|    |    | |   | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|    |    | |   | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|    |    | |   | |__ 0 for 8 bits, 1 for 16 bits
;|    |    | |   |__  Attribute name from above list (0..MAX)
;|    |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|    |    |__ Default value (left shifted as necessary)
;|    |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
;
;
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords 'TSTART' and '*** TEND ***'.
; The legend is 16 chars long.
; The correct number of values must be supplied (8-bits) with spaces in
; between.
;
;     EXAMPLE OF GOBO TABLE
;              __ Table width (upto 6 allowed)
;             |  __ Type of Table from attribute list
;             | |             _____________ Values in decimal
;     TSTART  2 11           |    |
;     01. O.W.              255  255
;     02. DOTS              235  255
;     03. CLOCK             225  255
;     04. CONE              215  255
;     05. WEAVE             205  255
;     *** TEND ***
;
; We also need to assign this table to a wheel so the following entry is required
; in the wheel information:
; 8  ffff 0    2  11 0 4   11 2  8  9 10  0  0  0  0  ; 3. GOBO TABLE
;              |  |    |   |  |  |  |  |  |  |  |  |___ 6th Channel
;              |  |    |   |  |  |  |  |  |  |  |___ 5th Channel
;              |  |    |   |  |  |  |  |  |  |___ 4th Channel
;              |  |    |   |  |  |  |  |  |___ 3rd Channel
;              |  |    |   |  |  |  |  |__ 2nd Channel of table
;              |  |    |   |  |  |  |___ 1st Channel of table
;              |  |    |   |  |  |__ 1st Channel of table (minus 1)
;              |  |    |   |  |___ Table Width
;              |  |    |   |_____ Table type (Attribute number)
;              |  |    |____ Wheel Number of table
;              |  |_____ Attribute Name
;              |____ Wheel Type (2 for table)
;
;
;
; Position Table.
;
; Color Table.
TSTART    3 4
White               255 255 255 
Red                 128  34   6 
Amber               179   2  55 
Yellow              255  25 220 
Green                36  46 244 
Cyan                 35 124 245 
Blue                 33 247  44 
Lavender             73 252  28 
UltraViolet           0 134   4 
Magenta             134 108   0 
lee 101             255   0 216 
lee 102             234  29 190 
lee 103             255  93 215 
lee 104             255   0 198 
lee 105             245  44 154 
lee 106             148  16  16 
lee 107             255 112 178 
lee 108             255  56 181 
lee 109             255  88 185 
lee 110             255  88 174 
lee 111             255  76  77 
lee 113             246  51   0 
lee 115              35  45 253 
lee 116               0  49 236 
lee 117             200 131 249 
lee 118              32  97 248 
lee 119              12 239 216 
lee 120               0 241 152 
lee 121             179   1 255 
lee 122              99  20 255 
lee 124              30   0 226 
lee 126             250 209  13 
lee 127             227  62  64 
lee 128             255 129   2 
lee 129               0   0   0 
lee 130             255 255 255 
lee 131              59  46 217 
lee 132              31 218 255 
lee 134             255  33 129 
lee 135             255   0  27 
lee 136             255 184 214 
lee 137             216 184 210 
lee 138             215  51 233 
lee 139              39   0 250 
lee 140             121  87 244 
lee 141              28 115 248 
lee 142             135 135 193 
lee 143              58  81 211 
lee 144              68  86 224 
lee 145               0   0   0 
lee 147             245  44 154 
lee 148             229  40  27 
lee 151             251 150 201 
lee 152             251  89 208 
lee 153             251  89 195 
lee 154             251  89 206 
lee 156             242  53 171 
lee 158             255  21  65 
lee 159             255 144 224 
lee 161             140 196 226 
lee 162             255 123 217 
lee 164              69 170 226 
lee 165              97 190 241 
lee 166             247  40  40 
lee 169             255 180 224 
lee 170             200 113 173 
lee 172              26  74 240 
lee 174             221 216 238 
lee 176             239  70 130 
lee 179             255   0 176 
lee 180              87 181  72 
lee 181               0 196  33 
lee 182             215   0   0 
lee 183               7  96 243 
lee 184               0   0   0 
lee 185               0   0   0 
lee 186               0   0   0 
lee 187               0   0   0 
lee 188               0   0   0 
lee 189               0   0   0 
lee 190               0   0   0 
*** TEND ****
;
;
;--------------------------------------------------------------------
; MACROS
; Each Macro is enclosed by the keywords 'MACRO' and 'MEND'.
;     EXAMPLE OF A MACRO:
;              __ Macro Name
;             |     __ Macro Number
;             |    |    _____ Channels controlled by macro
;             |    |   |  |
;     MACRO "HOME" 1  18  20
;     14   ff  ff
;     1    0   0 
;     MEND
;     Each entry consist of a time delay in 1/10s (in DECIMAL) followed by the
;     values to set the channels to in HEX.
; EG. The desk when executing the above macro will set channels 18&20 to 0xff
;     (255 in decimal) and then wait 1.4s. It then sets chan 18&20 to 0x0 and
;     waits 0.1s.
;
;
;
;
;
MACRO  "RESET" 1       1  2  3  4  5  6  7  8  9 10
 32     0  0  0  0  0  0  0  0  0  0 
MEND
