;-----------------------------------------------------------------------|
; The Clay Paky Alpha Spot Personality for the Diamond II               |
;-----------------------------------------------------------------------|
;       History :-                                                      |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;       1.0  | 12-07-04  | Phil   | Created from Alpha Wash             |
;---------------------------------------------------------------------- |


DEVICE=CP_ASpotStd              ; Device Name (upto 11 chars after '='
DEVICE23=16 channels            ; 22 chars after '='
            ; extra information for softkey prompt lines 2&3
                        ; a total of 22 chars, split into 2 lines of 11

; Device information
;                                   __ Number of lines of DMX info.
;                                  |   __ Number of lines of wheel info
;                                  |  |
;                                  |  |
;                                  |  |
HSTART  1 16 1b05 450 252 ff  0  4 16 16
;        | |  |    |   |   |  |  |
;        | |  |    |   |   |  |  |__ Line number for flash button DMX info
;        | |  |    |   |   |  |      from DMX definition (1..x)
;        | |  |    |   |   |  |__ Button release value
;        | |  |    |   |   |__ Button ON value (ff means use swop/add fader)
;        | |  |    |   |__ The TILT arc in Degrees
;        | |  |    |__ The Pan arc in degrees
;        | |  |__ Date in PC format (1b05==5/08/93)
;        | |__ Number of DMX slots used
;        |__ Patch direction (1-backward, 0 forward, (3 for moving head, 1 for Moving Mirror))


TEXTSTART               ; Upto 21 lines of 28 characters (use the template)
                            ;
                            ;
   CLAY PAKY Alpha Spot     ;
        PERSONALITY         ;
           Mode 1           ;
                            ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART                          ; DMX defintion
1  2 40 0 38 0      ; COLOUR1
2  2 40 0 39 0      ; COLOUR2
3  2 40 0 24 0      ; SHUTTER
4  1  0 0  0 0      ; DIMMER
5  2  0 0 15 0      ; IRIS
6  2 40 0 36 0      ; GOBO1
7  2  0 0 153 0      ; GOBO1ROT
8  2 40 0 37 0      ; GOBO2
9  2  0 0 154 0      ; GOBO2ROT
10 2  0 0 40 0      ; FROST
11 2  0 0 12 0      ; FOCUS
12 2  0 0 43 0      ; ZOOM
13 2  0 0 13 0      ; PAN
14 2  0 0 14 0      ; TILT
15 2 40 0 80 0      ; RESET
16 2 40 0 52 0      ; CONTROL

;|  |  | |  | |
;|  |  | |  | |__ Spare (always 0 for now)
;|  |  | |  |__ Attribute name (See list above)
;|  |  | |__ Curve (0 means no curve otherwise curve number)
;|  |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;|  |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition

WSTART
8 ffff    0 1  38 0  9   0 1  0  1  0  0  0  0  0  ; 1. COLOUR1
8 ffff    0 1  39 0 10   0 1  1  2  0  0  0  0  0  ; 2. COLOUR2
8 ffff 6969 1  24 0  1   0 1  2  3  0  0  0  0  0  ; 3. SHUTTER
8 ffff ffff 4   0 0  8   0 1  3  4  0  0  0  0  0  ; 4. DIMMER
8 ffff    0 1  15 0  2   0 1  4  5  0  0  0  0  0  ; 5. IRIS
8 ffff    0 1  36 0 17   0 1  5  6  0  0  0  0  0  ; 6. GOBO1
8 ffff    0 1 153 0 19   0 1  6  7  0  0  0  0  0  ; 7. GOBO1ROT
8 ffff    0 1  37 0 18   0 1  7  8  0  0  0  0  0  ; 8. GOBO2
8 ffff    0 1 154 0 20   0 1  8  9  0  0  0  0  0  ; 9. GOBO2ROT
8 ffff    0 1  40 0 25   0 1  9 10  0  0  0  0  0  ; 10. FROST
8 ffff 8080 3  12 0  3   0 1 10 11  0  0  0  0  0  ; 11. FOCUS
8 ffff    0 3  43 0  4   0 1 11 12  0  0  0  0  0  ; 12. ZOOM
8 ffff 8080 1  13 0  5   0 1 12 13  0  0  0  0  0  ; 13. PAN
8 ffff 8080 1  14 0  6   0 1 13 14  0  0  0  0  0  ; 14. TILT
8 ffff    0 1  80 0 41   0 1 14 15  0  0  0  0  0  ; 15. RESET
8 ffff    0 1  52 0 42   0 1 15 16  0  0  0  0  0  ; 16. CONTROL
;|   |    | |   | |  |   | |  |  |  |  |  |  |  |__ List of Table channels as
;|   |    | |   | |  |   | |  |  |_______________ line numbers from DMX def.
;|   |    | |   | |  |   | |  |                   0 means unused channel
;|   |    | |   | |  |   | |  |__ DMX line (minus 1) pertainig to this wheel
;|   |    | |   | |  |   | |__ Number of chanels under control OR Table width
;|   |    | |   | |  |   |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |   | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |   | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |   |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|_ Wheel multiplication =16-(bits used)
;eg. for 8 bit channels it is 8, for 12 bit channels it is 4
;
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between


;--------------------------------------------------------------------


