;-----------------------------------------------------------------------|
; The JB Lighting VaryLED A7 Zoom Personality for the Diamond II        |  
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By         | Description                    |
;------------|-----------|-------------|--------------------------------|
;   1.0      |  31-03-10 | John Rogers | Created from STARMK5Z.D2       |
;---------------------------------------------------------------------- |


DEVICE=VS_A7ZmSR16          ; Device Name (upto 11 chars after '='
DEVICE23=Std. 16bit
				; extra information for softkey prompt lines 2&3
				; a total of 22 chars, split into 2 lines of 11

; Device information
;                                    __ Number of lines of DMX info.
;                                   |    __ Number of lines of wheel info
;                                   |   |
;                                   |   |
;                                   |   |
HSTART  2  19 1b05 430 300 ff 0  4 19  14
;       |   |    |   |   |  | |  |
;       |   |    |   |   |  | |  |__ Line number for flash button DMX info
;       |   |    |   |   |  | |      from DMX definition (1..x)
;       |   |    |   |   |  | |__ Button release value
;       |   |    |   |   |  |__ Button ON value (ff means use swop/add fader)
;       |   |    |   |   |__ The TILT arc in Degrees
;       |   |    |   |__ The Pan arc in degrees
;       |   |    |__ Date in PC format (1b05==5/08/93)
;       |   |__ Number of DMX slots used
;       |__ Patch direction (1-backward, 0 forward, 2 for moving head)

TEXTSTART     		; Upto 21 lines of 28 characters (use the template below)
					;
JB Lighting         ; 
	                ;
VaryLED A7 Zoom     ;
					;
Standard, 16bit     ; 
                    ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition
DSTART              ; DMX defintion
1  2 20 0  13 0      ; PAN HIGH
2  0  0 0   0 0      ; PAN LOW
3  2 20 0  14 0      ; TILT HIGH
4  0  0 0   0 0      ; TILT LOW
5  2  0 0  52 0      ; Control 
6  2  0 0  24 0      ; Shutter
7  1  0 0   0 0      ; Dimmer
8  2  0 0  43 0      ; Zoom
9  2 20 0   5 0      ; Red
10 0  0 0   0 0      ; Red Low
11 2 20 0  10 0      ; Green
12 0  0 0   0 0      ; Green Low
13 2 20 0   6 0      ; Blue
14 0  0 0   0 0      ; Blue Low
15 2  0 0 149 0      ; CTO
16 2  0 0   4 0      ; Colour
17 2  0 0  58 0      ; PT Speed
18 2  0 0 106 0      ; Effect Speed
19 2  0 0 133 0      ; Blackout On Movement
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 40=instant, 20=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines))
;|_ DMX offset (1..255, 0 means DIMMER will be patched seperately)
;
;
;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition

WSTART
 0 ffff 8000 3  13 1  5  0 1  0  1  0  0  0  0  0  ; 1.  Pan
 0 ffff 8000 3  14 1  6  0 1  2  3  0  0  0  0  0  ; 2.  Tilt
 8 ffff 0000 1  52 0 41  0 1  4  5  0  0  0  0  0  ; 3.  Control
 8 ffff ffff 1  24 0  7  0 1  5  6  0  0  0  0  0  ; 4.  Shutter
 8 ffff ffff 4   0 0  8  0 1  6  7  0  0  0  0  0  ; 5.  DIMMER
 8 ffff 8080 1  43 0 33  0 1  7  8  0  0  0  0  0  ; 6.  Zoom
 0 ffff ffff 1   5 1 13  0 1  8  9  0  0  0  0  0  ; 4.  Red
 0 ffff ffff 1  10 1 14  0 1 10 11  0  0  0  0  0  ; 5.  Green
 0 ffff ffff 1   6 1 15  0 1 12 13  0  0  0  0  0  ; 6.  Blue 
 8 ffff 0000 1 149 0 12  0 1 14 15  0  0  0  0  0  ; 2.  CTO
 8 ffff 0000 1   4 0 11  0 1 15 16  0  0  0  0  0  ; 3.  Colour
 8 ffff 0000 1  58 0 27  0 1 16 17  0  0  0  0  0  ; 9.  PT Speed
 8 ffff    0 1 106 0 28  0 1 17 18  0  0  0  0  0  ; 13. Effect Speed
 8 ffff    0 1 133 0 42  0 1 18 19  0  0  0  0  0  ; 14. Blackout On Movement
;A BBBB CCCC D   E F  G  H I  J  K  L  L  L  L  L		;Name
;|    |    | |   | |  |  | |  |  |  |  |  |  |  |__L. List of Table channels as
;|    |    | |   | |  |  | |  |  |___K. line numbers from DMX def.
;|    |    | |   | |  |  | |  |         0 means unused channel
;|    |    | |   | |  |  | |  |__J. DMX line (minus 1) pertainig to this wheel
;|    |    | |   | |  |  | |__I. Number of channels under control OR Table width
;|    |    | |   | |  |  |__H. Table type (Attribute number) 0 means NOT a table
;|    |    | |   | |  |__G. Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|    |    | |   | |__F. 0 for 8 bits, 1 for 16 bits
;|    |    | |   |__E.  Attribute name from above list (0..MAX)
;|    |    | |__D. Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|    |    |__C. Default/Locate value (left shifted as necessary)
;|    |__B. AND mask, where more than wheel controls same DMX slot
;|__A. Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;;--------------------------------------------------------------------
