;-----------------------------------------------------------------------|
; The Elation design Spot 250     Personality for the Diamond II        | 
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;   1.0      |  22-03-06 | Ed S   | Created                             |
;---------------------------------------------------------------------- |


DEVICE=EL_DesSp250          ; Device Name (upto 11 chars after '='
DEVICE23=16 Chans
						; extra information for softkey prompt lines 2&3
						; a total of 22 chars, split into 2 lines of 11

; Device information
;                                    __ Number of lines of DMX info.
;                                   |    __ Number of lines of wheel info
;                                   |   |
;                                   |   |
;                                   |   |
HSTART  2  16 1b05 530 280 ff 0  4  16  14
;       |   |    |   |   |  | |  |
;       |   |    |   |   |  | |  |__ Line number for flash button DMX info
;       |   |    |   |   |  | |      from DMX definition (1..x)
;       |   |    |   |   |  | |__ Button release value
;       |   |    |   |   |  |__ Button ON value (ff means use swop/add fader)
;       |   |    |   |   |__ The TILT arc in Degrees
;       |   |    |   |__ The Pan arc in degrees
;       |   |    |__ Date in PC format (1b05==5/08/93)
;       |   |__ Number of DMX slots used
;       |__ Patch direction (1-backward, 0 forward, 2 for moving head)

TEXTSTART               ; Upto 21 lines of 28 characters (use the template)
                            ;
                            ;
  Elation Design Spot250    ;
         16DMX              ;
                            ;
                            ;
                            ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition
DSTART              ; DMX defintion
1  2 20 0  13 0      ; PAN HIGH
2  0  0 0   0 0      ; PAN LOW
3  2 20 0  14 0      ; TILT HIGH
4  0  0 0   0 0      ; TILT LOW
5  2 40 0  38 0      ; Colour
6  2 40 0  36 0      ; Gobo 1
7  2 40 0  64 0      ; Gobo 1 spin
8  2 40 0  37 0      ; Gobo 2
9  2  0 0  16 0      ; Prism
10 2  0 0  12 0      ; Focus
11 2  0 0  24 0      ; Shutter
12 1  0 0   0 0      ; Dimmer
13 2  0 0  15 0      ; Iris
14 2  0 0  40 0      ; Frost
15 2 40 0  58 0      ; Speed PT
16 2 40 0  52 0      ; Control
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|_ DMX offset (1..255, 0 means DIMMER will be patched seperately)
;
;
;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition

WSTART
6 ffff 8000 3  13 1  5  0 1  0  1  0  0  0  0  0  ; 1. PAN
6 ffff 8000 3  14 1  6  0 1  2  3  0  0  0  0  0  ; 3. TILT
8 ffff    0 1  38 0  9  0 1  4  5  0  0  0  0  0  ; 5. Colour
8 ffff    0 1  36 0 17  0 1  5  6  0  0  0  0  0  ; 6. Gobo 1
8 ffff    0 1  64 0 18  0 1  6  7  0  0  0  0  0  ; 7. Gobo 1 Spin
8 ffff    0 1  37 0 19  0 1  7  8  0  0  0  0  0  ; 8. Gobo 2
8 ffff    0 1  16 0 25  0 1  8  9  0  0  0  0  0  ; 9. Prism
8 ffff    0 1  12 0 33  0 1  9 10  0  0  0  0  0  ; 10.Focus
8 ffff 3030 1  24 0  7  0 1 10 11  0  0  0  0  0  ; 11.Shutter
8 ffff ffff 4   0 0  8  0 1 11 12  0  0  0  0  0  ; 12.DIMMER
8 ffff 8080 1  15 0  2  0 1 12 13  0  0  0  0  0  ; 13.Iris
8 ffff    0 1  40 0 34  0 1 13 14  0  0  0  0  0  ; 14.Frost
8 ffff    0 1  58 0 28  0 1 14 15  0  0  0  0  0  ; 15.Speed PT
8 ffff ffff 1  52 0 41  0 1 15 16  0  0  0  0  0  ; 16. Control
;|   |    | |  | |  |  | |  |  |  |  |  |  |  |__ List of Table channels as 
;|   |    | |  | |  |  | |  |  |_______________ line numbers from DMX def.
;|   |    | |  | |  |  | |  |                   0 means unused channel
;|   |    | |  | |  |  | |  |__ DMX line (minus 1) pertainig to this wheel
;|   |    | |  | |  |  | |__ Number of channels under control OR Table width
;|   |    | |  | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |  | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |  | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |  |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;;--------------------------------------------------------------------



; Macros
MACRO "Lamp On"       1  16
0  32
1  3C
0   A
1   A
MEND

MACRO "Lamp Off"      2  16
0  46
1  3C
0   A
1   A
MEND


MACRO "Reset All"     3  16
0  52
1  3C
0   A
1   A
MEND


