#!/bin/bash

dbicdump -o dump_directory=../frontend/webui2/lib \
    -o components='["InflateColumn::DateTime"]' \
    -o preserve_case=1 \
    DB dbi:mysql:database=rdmx root warp242 '{ quote_char => "`" }'


