;-----------------------------------------------------------------------|
; The STUDIO DUE LIVE PRO 1200 Personality for the Diamond II           | 
;-----------------------------------------------------------------------|
;       History :-                                                      |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;       1.0  |  09-05-97 |  Anwar | Created                             |
;       1.1  |  05-06-97 |  DBT   | Set to moving head                  |
;---------------------------------------------------------------------- |


DEVICE=SD_LPRO1200              ; Device Name (upto 11 chars after '='
DEVICE23=STUDIO DUE             ; 22 chars after '='
                        ; extra information for softkey prompt lines 2&3
                                                ; a total of 22 chars, split into 2 lines of 11

; Device information
;                                   __ Number of lines of DMX info.
;                                  |   __ Number of lines of wheel info
;                                  |  |
;                                  |  |
;                                  |  |
HSTART   3 20 1b05 360 300 ff 0  9 20 19
;        | |   |    |   |  |  |  |
;        | |   |    |   |  |  |  |__ Line number for flash button DMX info
;        | |   |    |   |  |  |      from DMX definition (1..x)
;        | |   |    |   |  |  |__ Button release value
;        | |   |    |   |  |__ Button ON value (ff means use swop/add fader)
;        | |   |    |   |__ The TILT arc in Degrees
;        | |   |    |__ The Pan arc in degrees
;        | |   |__ Date in PC format (1b05==5/08/93)
;        | |__ Number of DMX slots used
;        |__ (1-mirror, 3 for moving head)


TEXTSTART               ; Upto 21 lines of 28 characters (use the template)
                            ;
                            ;
   STUDIO DUE               ;
   LIVE PRO 1200            ;
                            ;
   20 DMX Channels          ; 
   Setting AUX=OFF          ;
TEXTEND
;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART                          ; DMX defintion
1  2  0 0 15 0      ; IRIS
2  2 40 0 38 0      ; COLOR WHEEL 1
3  2 40 0 36 0      ; GOBO1
4  2 40 0 17 0      ; Strobe
5  2 20 0 13 0          ; PAN
6  0  0 0  0 0      ; Dummy for 16-bit channels 
7  2 20 0 14 0          ; TILT
8  0  0 0  0 0      ; Dummy for 16-bit channels 
9  1  0 0  0 0      ; DIMMER
10 2 40 0 25 0      ; SPEED
11 2 40 0 12 0      ; FOCUS/ZOOM
12 2 40 0 39 0      ; COLOR WHEEL 2
13 2 40 0 37 0      ; GOBO2
14 2 40 0 49 0      ; GOBO MODE
15 2  0 0  7 0      ; MAGENTA
16 2  0 0  8 0      ; CYAN
17 2  0 0  9 0      ; YELLOW
18 2 40 0 40 0      ; FROST
19 2 40 0 78 0      ; Prism Rotate
20 2 40 0 52 0      ; CONTROL
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition

WSTART
8 ffff 8080 1  15 0  1   0 1  0  1  0  0  0  0  0  ; 1. IRIS
8 ffff    0 1  38 0  4   0 1  1  2  0  0  0  0  0  ; 2. COLOR WHEEL 
8 ffff    0 1  36 0 17   0 1  2  3  0  0  0  0  0  ; 3. GOBO1
8 ffff    0 1  17 0 26   0 1  3  4  0  0  0  0  0  ; 4. SHUTTER
6 ffff 8000 3  13 1  5   0 1  4  5  0  0  0  0  0  ; 5. PAN
6 ffff 8000 3  14 1  6   0 1  6  7  0  0  0  0  0  ; 6. TILT
8 ffff ffff 4   0 0  8   0 1  8  9  0  0  0  0  0  ; 7. DIMMER
8 ffff ffff 1  25 0 28   0 1  9 10  0  0  0  0  0  ; 8. SPEED
8 ffff 4040 1  12 0  2   0 1 10 11  0  0  0  0  0  ; 9. FOCUS/ZOOM
8 ffff    0 1  39 0  9   0 1 11 12  0  0  0  0  0  ; 10. COLOR WHEEL 2
8 ffff    0 1  37 0 19   0 1 12 13  0  0  0  0  0  ; 11. GOBO2
8 ffff    0 1  49 0 20   0 1 13 14  0  0  0  0  0  ; 12. GOBO MODE
8 ffff    0 1   7 0 11   0 1 14 15  0  0  0  0  0  ; 13. MAGENTA
8 ffff    0 1   8 0 10   0 1 15 16  0  0  0  0  0  ; 14. CYAN
8 ffff    0 1   9 0 12   0 1 16 17  0  0  0  0  0  ; 15. YELLOW
8 ffff    0 1  40 0 25   0 1 17 18  0  0  0  0  0  ; 16. FROST
8 ffff    0 1  78 0 15   0 1 18 19  0  0  0  0  0  ; 17. Prism ROTATION
8 ffff    0 1  52 0 41   0 1 19 20  0  0  0  0  0  ; 18. CONTROL
8 ffff    0 2 103 0  3 103 3 14 17 15 16  0  0  0  ; 19. LEE TABLE
;|   |    | |  |  |  |  |  |  |  |  |  |  |  |  |__ List of Table channels as 
;|   |    | |  |  |  |  |  |  |  |_______________ line numbers from DMX def.
;|   |    | |  |  |  |  |  |  |                   0 means unused channel
;|   |    | |  |  |  |  |  |  |__ DMX line (minus 1) pertainig to this wheel
;|   |    | |  |  |  |  |  |__ Number of chanels under control OR Table width
;|   |    | |  |  |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |  |  |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |  |  |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |  |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;       eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between

;Lee Colours
TSTART  3  103
lee101                  0       157     0
lee102                  15      104     104
lee103                  175     189     185
lee104                  177     202     199
lee105                  184     212     212
lee106                  117     191     207
lee107                  101     100     86
lee108                  102     127     33
lee109                  111     114     59
lee110                  108     109     62
lee111                  21      71      148
lee113                  81      125     255
lee115                  148     119     8
lee116                  170     99      84
lee117                  128     117     33
lee118                  234     60      114
lee119                  255     92      169
lee120                  255     99      179
lee121                  155     177     118
lee122                  154     191     1
lee124                  255     127     102
lee126                  58      36      255
lee127                  12      81      158
lee128                  0       90      213
lee129                  255     255     255
lee130                  0       0       0
lee131                  137     128     0
lee132                  239     31      125
lee134                  120     141     0
lee135                  116     175     165
lee136                  86      60      0
lee137                  72      1       0
lee138                  5       90      0
lee139                  205     253     13
lee140                  135     119     4
lee141                  255     0       1
lee142                  142     98      94
lee143                  143     107     0
lee144                  133     109     0
lee145                  255     255     255
lee147                  193     198     193
lee148                  94      122     200
lee151                  25      77      111
lee152                  23      63      108
lee153                  97      104     60
lee154                  74      99      28
lee156                  82      96      95
lee158                  119     208     17
lee159                  41      72      3
lee161                  137     101     1
lee162                  78      93      51
lee164                  132     201     131
lee165                  133     106     33
lee166                  0       96      160
lee169                  65      33      0
lee170                  87      67      0
lee172                  162     91      79
lee174                  126     108     6
lee176                  42      84      140
lee179                  92      144     0
lee180                  115     33      79
lee181                  158     34      201
lee182                  108     156     201
lee183                  154     97      0
lee184                  62      88      0
lee185                  76      86      0
lee186                  4       33      106
lee187                  4       70      101
lee188                  5       59      100
lee189                  58      83      0
lee190                  39      78      31
lee191                  2       9       67
lee192                  7       73      147
lee193                  174     193     212
lee194                  85      19      0
lee195                  211     96      178
lee196                  132     99      74
lee197                  137     121     86
*** TEND ***

