;-----------------------------------------------------------------------|
; The High End Catalyst ver 3. Personality for the Diamond II/III   |
;-----------------------------------------------------------------------|
;       History :-                                                      |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By      | Description                       |
;------------|-----------|----------|-----------------------------------|
;       1.0  |  29-01-04 |Greg Brown| Created                           |
;       1.1  |  29-07-04 |Phil      | Updated locate values             |
;---------------------------------------------------------------------- |


DEVICE=HE_CATv3                 ; Device Name (upto 11 chars after '='
DEVICE23=40 CHANNELS            ; 22 chars after '='
	             		; extra information for softkey prompt lines 2&3
						; a total of 22 chars, split into 2 lines of 11

; Device information
;                                   __ Number of lines of DMX info.
;                                  |   __ Number of lines of wheel info
;                                  |  |
;                                  |  |
;                                  |  |
HSTART  1 40 1b05  0   0 ff 0  1 40 32
;        | |  |    |   |  |  |  |
;        | |  |    |   |  |  |  |__ Line number for flash button DMX info
;        | |  |    |   |  |  |      from DMX definition (1..x)
;        | |  |    |   |  |  |__ Button release value
;        | |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;        | |  |    |   |__ The TILT arc in Degrees
;        | |  |    |__ The Pan arc in degrees
;        | |  |__ Date in PC format (1b05==5/08/93)
;        | |__ Number of DMX slots used
;        |__ Patch direction (0 for mirror, 3 for moving head)


TEXTSTART                 ; Upto 21 lines of 28 characters (use the template)
                                 ;
                                 ;
    High End Catalyst ver. 3     ;
      40 Channels                ;
                                 ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition
DSTART               ; DMX defintion
1  2 40 0 173 0      ; LIBRARY
2  2 40 0 174 0      ; FILE
3  2 20 0 175 0      ; INFRAME
4  0  0 0   0 0      ; INFRAMELO
5  2 20 0 177 0      ; OUTFRAME
6  0  0 0   0 0      ; OUTFRMAELO
7  2 40 0 179 0      ; PLAY
8  2  0 0 180 0      ; PLAYSPEED
9  2 20 0 185 0      ; X-ROT
10 0  0 0   0 0      ; X-ROTLO
11 2 20 0 187 0      ; Y-ROT
12 0  0 0   0 0      ; Y-ROTLO
13 2 20 0 189 0      ; Z-ROT
14 0  0 0   0 0      ; Z-ROTLO
15 2 20 0 191 0      ; SCALE
16 0  0 0   0 0      ; SCALELO
17 2 20 0 193 0      ; X-POS
18 0  0 0   0 0      ; X-POSLO
19 2 20 0 195 0      ; Y-POS
20 0  0 0   0 0      ; Y-POSLO
21 2  0 0 197 0      ; ASPECTRATIO
22 2  0 0  25 0      ; MSPEED
23 1  0 0   0 0      ; DIMMER
24 2  0 0   5 0      ; RED
25 2  0 0  10 0      ; GREEN
26 2  0 0   6 0      ; BLUE
27 2 40 0  17 0      ; STROBE
28 2  0 0 138 0      ; TRAIL (DELAY)
29 2 40 0 81  0      ; COLFX
30 2 40 0 160 0      ; VISFUNCTION
31 2  0 0 161 0      ; VIS1
32 2  0 0 162 0      ; VIS2
33 2  0 0 163 0      ; KEYSTONE 1X
34 2  0 0 164 0      ; KEYSTONE 1Y
35 2  0 0 165 0      ; KEYSTONE 2X
36 2  0 0 166 0      ; KEYSTONE 2Y
37 2  0 0 167 0      ; KEYSTONE 3X
38 2  0 0 168 0      ; KEYSTONE 3Y
39 2  0 0 169 0      ; KEYSTONE 4X
40 2  0 0 170 0      ; KEYSTONE 4Y
;| |  | |   | |
;| |  | |   | |__ Spare (always 0 for now)
;| |  | |   |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition
WSTART
8 ffff 0000 1 173 0 41  0 1  0  1  0  0  0  0  0 ; Library
8 ffff 0000 1 174 0 42  0 1  1  2  0  0  0  0  0 ; File
4 ffff 0000 1 175 1 43  0 1  2  3  0  0  0  0  0 ; IN Frame
4 ffff 0000 1 177 1 44  0 1  4  5  0  0  0  0  0 ; Out Frame
8 ffff 0000 1 179 0  7  0 1  6  7  0  0  0  0  0 ; Play
8 ffff 0000 1 180 0 15  0 1  7  8  0  0  0  0  0 ; Play Speed
4 ffff 8000 1 185 1 33  0 1  8  9  0  0  0  0  0 ; X-Rot
4 ffff 8000 1 187 1 34  0 1 10 11  0  0  0  0  0 ; Y-Rot
4 ffff 8000 1 189 1 35  0 1 12 13  0  0  0  0  0 ; Z-Rot
4 ffff 9000 1 191 1 36  0 1 14 15  0  0  0  0  0 ; Scale
4 ffff 8080 1 193 1  5  0 1 16 17  0  0  0  0  0 ; X-Pos
4 ffff 8080 1 195 1  6  0 1 18 19  0  0  0  0  0 ; Y-Pos
8 ffff 0000 1 197 0 39  0 1 20 21  0  0  0  0  0 ; Aspect Ratio
8 ffff 0000 1  25 0 47  0 1 21 22  0  0  0  0  0 ; MSpeed
8 ffff 0000 1   0 0  8  0 1 22 23  0  0  0  0  0 ; Dimmer
8 ffff ffff 1   5 0  2  0 1 23 24  0  0  0  0  0 ; Red
8 ffff ffff 1  10 0  3  0 1 24 25  0  0  0  0  0 ; Green
8 ffff ffff 1   6 0  4  0 1 25 26  0  0  0  0  0 ; Blue
8 ffff 0000 1  17 0 28  0 1 26 27  0  0  0  0  0 ; Strobe
8 ffff 0000 1 138 0 31  0 1 27 28  0  0  0  0  0 ; Trail (DELAY)
8 ffff 0000 1  81 0  1  0 1 38 29  0  0  0  0  0 ; COlFx
8 ffff 0000 1 160 0 25  0 1 29 30  0  0  0  0  0 ; VisFunction
8 ffff 0000 1 161 0 26  0 1 30 31  0  0  0  0  0 ; Vis1
8 ffff 0000 1 162 0 27  0 1 31 32  0  0  0  0  0 ; Vis2
8 ffff 8080 1 163 0  9  0 1 32 33  0  0  0  0  0 ; Keystone x1
8 ffff 8080 1 164 0 10  0 1 33 34  0  0  0  0  0 ; Keystone y1
8 ffff 8080 1 165 0 11  0 1 34 35  0  0  0  0  0 ; Keystone x2
8 ffff 8080 1 166 0 12  0 1 35 36  0  0  0  0  0 ; Keystone y2
8 ffff 8080 1 167 0 17  0 1 36 37  0  0  0  0  0 ; Keystone x3
8 ffff 8080 1 168 0 18  0 1 37 38  0  0  0  0  0 ; Keystone y3
8 ffff 8080 1 169 0 19  0 1 38 39  0  0  0  0  0 ; Keystone x4
8 ffff 8080 1 170 0 20  0 1 39 40  0  0  0  0  0 ; Keystone y4
;|   |    | |   | |  |  | |  |  |  |  |  |  |  |__ List of Table channels as 
;|   |    | |   | |  |  | |  |  |_______________ line numbers from DMX def.
;|   |    | |   | |  |  | |  |                   0 means unused channel
;|   |    | |   | |  |  | |  |__ DMX line (minus 1) pertainig to this wheel
;|   |    | |   | |  |  | |__ Number of chanels under control OR Table width
;|   |    | |   | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |   | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |   | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |   |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between
;--------------------------------------------------------------------
