;-----------------------------------------------------------------------|
; RObe RedWash 3.192 Mode 2 personality for the Diamond II              |
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By       | Description                      |
;------------|-----------|-----------|----------------------------------|
;   1.0      |  24-07-09 | David Hunt| Created		                |
;---------------------------------------------------------------------- |


DEVICE=RO_RW3192m2      ; Device Name (upto 11 chars) must be enclosed in single
DEVICE23=               ; 22 chars after '='
                        ; extra information for softkey prompt lines 2&3
                        ; a total of 22 chars, split into 2 lines of 11

;                                  __ Number of lines of DMX info.
;                                 |   __ Number of lines of wheel info
;                                 |  |
;                                 |  |
;                                 |  |
HSTART  3 24 1b05 530 285 ff 0 8 24 23
;       |  |  |    |   |  |  | |
;       |  |  |    |   |  |  | |__ Line number for flash button DMX info
;       |  |  |    |   |  |  |     from DMX definition (1..x)
;       |  |  |    |   |  |  |__ Button release value
;       |  |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;       |  |  |    |   |__ The TILT arc in Degrees
;       |  |  |    |__ The Pan arc in degrees
;       |  |  |__ Date in PC format (1b05==5/08/93)
;       |  |__ Number of DMX slots used
;       |__ Patch direction (1-backward, 2 forward)




TEXTSTART       ; Upto 21 lines of 28 characters
                            ;
         Robe               ;
     RedWash 3.192          ;
         Mode 2             ;
       PERSONALITY          ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART               ; DMX Picture
1  2 20 0  13 0      ; PAN
2  2 20 0  14 0      ; TILT
3  2  0 0  58 0      ; PT Speed
4  2  0 0  52 0      ; Control
5  2  0 0   5 0      ; Red 1
6  2  0 0  10 0      ; Green 1
7  2  0 0   6 0      ; Blue 1
8  2  0 0  38 0      ; White 1
9  2  0 0   8 0      ; Red 2
10 2  0 0   7 0      ; Green 2
11 2  0 0   9 0      ; Blue 2
12 2  0 0  39 0      ; White 2
13 2  0 0  28 0      ; Red 3
14 2  0 0  29 0      ; Green 3
15 2  0 0  30 0      ; Blue 3
16 2  0 0  76 0      ; White 3
17 2  0 0 149 0      ; Red 4
18 2  0 0 150 0      ; Green 4
19 2  0 0  81 0      ; Blue 4
20 2  0 0  85 0      ; White 4
21 2  0 0  48 0      ; ColourMacro
22 2  0 0  24 0      ; SHUTTER
23 1 20 0   0 0      ; Dimmer
24 0  0 0   0 0      ; Dimmer low
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information

WSTART
4 ffff 8080 3  13 0  5  0  1  0  1  0  0  0  0  0      ; 1. PAN
4 ffff 8080 3  14 0  6  0  1  1  2  0  0  0  0  0      ; 2. TILT
8 ffff    0 1  58 0 42  0  1  2  3  0  0  0  0  0      ; 3. PT Speed
8 ffff    0 1  52 0 41  0  1  3  4  0  0  0  0  0      ; 4. Control
8 ffff ffff 1   5 0  9	0  1  4  5  0  0  0  0  0      ; 5. Red 1
8 ffff ffff 1  10 0 10  0  1  5  6  0  0  0  0  0      ; 6. Green 1
8 ffff ffff 1   6 0 11  0  1  6  7  0  0  0  0  0      ; 7. Blue 1
8 ffff ffff 1  38 0 12  0  1  7  8  0  0  0  0  0      ; 8. White 1
8 ffff ffff 1   8 0 17	0  1  8  9  0  0  0  0  0      ; 9. Red 2
8 ffff ffff 1   7 0 18  0  1  9 10  0  0  0  0  0      ;10. Green 2
8 ffff ffff 1   9 0 19  0  1 10 11  0  0  0  0  0      ;11. Blue 2
8 ffff ffff 1  39 0 20  0  1 11 12  0  0  0  0  0      ;12. White 2
8 ffff ffff 1  28 0 25	0  1 12 13  0  0  0  0  0      ;13. Red 3
8 ffff ffff 1  29 0 26  0  1 13 14  0  0  0  0  0      ;14. Green 3
8 ffff ffff 1  30 0 27  0  1 14 15  0  0  0  0  0      ;15. Blue 3
8 ffff ffff 1  76 0 28  0  1 15 16  0  0  0  0  0      ;16. White 3
8 ffff ffff 1 149 0 33	0  1 16 17  0  0  0  0  0      ;17. Red 4
8 ffff ffff 1 150 0 34  0  1 17 18  0  0  0  0  0      ;18. Green 4
8 ffff ffff 1  81 0 35  0  1 18 19  0  0  0  0  0      ;19. Blue 4
8 ffff ffff 1  85 0 36  0  1 19 20  0  0  0  0  0      ;20. White 4
8 ffff    0 1  48 0 15  0  1 20 21  0  0  0  0  0      ;21. ColourMacro
8 ffff 2323 1  24 0  7  0  1 21 22  0  0  0  0  0      ;22. Shutter
4 ffff ffff 4   0 0  8  0  1 22 23  0  0  0  0  0      ;23. Dimmer
;|   |    | |  | |  |  |  |  |  |  |  |  |  |  |__ List of Table channels as
;|   |    | |  | |  |  |  |  |  |_______________ line numbers from DMX def.
;|   |    | |  | |  |  |  |  |                  ff or 0 means unused channel
;|   |    | |  | |  |  |  |  |__ DMX line pertainnig to this wheel (-1)
;|   |    | |  | |  |  |  |__ Number of chanels under control (Table width)
;|   |    | |  | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |  | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |  | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |  |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tile, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;    eg. for 8 bit channels it is 8, for 12 bit channels it is 4




;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between
;--------------------------------------------------------------------



