;-----------------------------------------------------------------------|
; Robe Colour Spot 170 AT  personality for the Diamond II       	|
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By       | Description                      |
;------------|-----------|-----------|----------------------------------|
;	     |  15-03-06 | E Spencer | Created		                |
;---------------------------------------------------------------------- |


DEVICE=AK_OP-80_M1       ; Device Name (upto 11 chars) must be enclosed in single
DEVICE23=24             ; 22 chars after '='
                        ; extra information for softkey prompt lines 2&3
                        ; a total of 22 chars, split into 2 lines of 11

;                                  __ Number of lines of DMX info.
;                                 |   __ Number of lines of wheel info
;                                 |  |
;                                 |  |
;                                 |  |
HSTART  3 24 1b05  0   0 ff 0 8  24 24
;       |  |  |    |   |  |  | |
;       |  |  |    |   |  |  | |__ Line number for flash button DMX info
;       |  |  |    |   |  |  |     from DMX definition (1..x)
;       |  |  |    |   |  |  |__ Button release value
;       |  |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;       |  |  |    |   |__ The TILT arc in Degrees
;       |  |  |    |__ The Pan arc in degrees
;       |  |  |__ Date in PC format (1b05==5/08/93)
;       |  |__ Number of DMX slots used
;       |__ Patch direction (1-backward, 2 forward)




TEXTSTART       ; Upto 21 lines of 28 characters
                            ;
  Alkalite Octopod OP-80    ;
       Mode 1 48DMX         ;
        Patch twice         ;
   2nd patch should be at   ;
     base address +24       ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART              ; DMX Picture 
1  2  0 0  38 0     ; Col1
2  2  0 0  39 0     ; Col2
3  2  0 0  84 0     ; Col3
4  2  0 0  85 0     ; Col4
5  2  0 0   5 0     ; Red1
6  2  0 0   4 0     ; Red2
7  2  0 0 159 0     ; Red3
8  2  0 0  48 0     ; Red4
9  2  0 0  10 0     ; Green1
10 2  0 0 163 0     ; Green2
11 2  0 0 164 0     ; Green3
12 2  0 0 165 0     ; Green4
13 2  0 0   6 0     ; Blue1
14 2  0 0 166 0     ; Blue2
15 2  0 0 167 0     ; Blue3
16 2  0 0 168 0     ; Blue4
17 2  0 0  67 0     ; Shutter1
18 2  0 0  68 0     ; Shutter2
19 2  0 0  69 0     ; Shutter3
20 2  0 0  70 0     ; Shutter4
21 2  0 0  51 0     ; Effect1
22 2  0 0  86 0     ; Effect2
23 2  0 0  41 0     ; Effect3
24 2  0 0 106 0     ; Effect4
;| |  | |   | |
;| |  | |   | |__ Spare (always 0 for now)
;| |  | |   |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information

WSTART
8 ffff    0 1  38 0  9  0  1 0  1  0  0  0  0  0      ; 1. Col1
8 ffff    0 1  39 0 10  0  1 1  2  0  0  0  0  0      ; 2. Col2
8 ffff    0 1  84 0 11  0  1 2  3  0  0  0  0  0      ; 3. Col3
8 ffff    0 1  85 0 12  0  1 3  4  0  0  0  0  0      ; 4. Col4
8 ffff    0 1   5 0 25  0  1 4  5  0  0  0  0  0      ; 5. Red1
8 ffff    0 1   4 0 26  0  1 5  6  0  0  0  0  0      ; 6. Red2
8 ffff    0 1 159 0 27  0  1 6  7  0  0  0  0  0      ; 7. Red3
8 ffff    0 1  48 0 28  0  1 7  8  0  0  0  0  0      ; 8. Red4
8 ffff    0 1  10 0 33  0  1 8  9  0  0  0  0  0      ; 9. Green1
8 ffff    0 1 163 0 34  0  1 9  10 0  0  0  0  0      ; 10.Green2
8 ffff    0 1 164 0 35  0  1 10 11 0  0  0  0  0      ; 11.Green3
8 ffff    0 1 165 0 36  0  1 11 12 0  0  0  0  0      ; 12.Green4
8 ffff    0 1   6 0 41  0  1 12 13 0  0  0  0  0      ; 13.Blue1
8 ffff    0 1 166 0 42  0  1 13 14 0  0  0  0  0      ; 14.Blue2
8 ffff    0 1 167 0 43  0  1 14 15 0  0  0  0  0      ; 15.Blue3
8 ffff    0 1 168 0 44  0  1 15 16 0  0  0  0  0      ; 16.Blue4
8 ffff    0 1  67 0  1  0  1 16 17 0  0  0  0  0      ; 17.Shutter1
8 ffff    0 1  68 0  2  0  1 17 18 0  0  0  0  0      ; 18.Shutter2
8 ffff    0 1  69 0  3  0  1 18 19 0  0  0  0  0      ; 19.Shutter3
8 ffff    0 1  70 0  4  0  1 19 20 0  0  0  0  0      ; 20.Shutter4
8 ffff    0 1  51 0 17  0  1 20 21 0  0  0  0  0      ; 21.Effect1
8 ffff    0 1  86 0 18  0  1 21 22 0  0  0  0  0      ; 22.Effect2
8 ffff    0 1  41 0 19  0  1 22 23 0  0  0  0  0      ; 23.Effect3
8 ffff    0 1 106 0 20  0  1 23 24 0  0  0  0  0      ; 24.Effect4
;|   |    | |  | |  |  |  |  |  |  |  |  |  |  |__ List of Table channels as
;|   |    | |  | |  |  |  |  |  |_______________ line numbers from DMX def.
;|   |    | |  | |  |  |  |  |                  ff or 0 means unused channel
;|   |    | |  | |  |  |  |  |__ DMX line pertainnig to this wheel (-1)
;|   |    | |  | |  |  |  |__ Number of chanels under control (Table width)
;|   |    | |  | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |  | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |  | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |  |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;    eg. for 8 bit channels it is 8, for 12 bit channels it is 4




;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between


;--------------------------------------------------------------------



