;-----------------------------------------------------------------------|
; The High End Technobeam Hi-Res Personality for the Diamond II         | 
;-----------------------------------------------------------------------|
;       History :-                                                      |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;       1.0  |  25-02-98 | P.Bari | Created                             | 
;---------------------------------------------------------------------- |


DEVICE=HE_TechbmHi              ; Device Name (upto 11 chars after '='
DEVICE23=18 CHANNELS            ; 22 chars after '='
	             		; extra information for softkey prompt lines 2&3
						; a total of 22 chars, split into 2 lines of 11

; Device information
;                                   __ Number of lines of DMX info.
;                                  |   __ Number of lines of wheel info
;                                  |  |
;                                  |  |
;                                  |  |
HSTART  1 18 1b05 170 108 ff 0  1 18 15
;        | |  |    |   |  |  |  |
;        | |  |    |   |  |  |  |__ Line number for flash button DMX info
;        | |  |    |   |  |  |      from DMX definition (1..x)
;        | |  |    |   |  |  |__ Button release value
;        | |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;        | |  |    |   |__ The TILT arc in Degrees
;        | |  |    |__ The Pan arc in degrees
;        | |  |__ Date in PC format (1b05==5/08/93)
;        | |__ Number of DMX slots used
;        |__ Patch direction (0 for mirror, 3 for moving head)


TEXTSTART                 ; Upto 21 lines of 28 characters (use the template)
                                 ;
                                 ;
  High End Technobeam            ;
  Hi-Res (18 Channels)           ;
     Personality                 ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition
DSTART              ; DMX defintion
1  2 20 0  13 0      ; PAN
2  0  0 0   0 0      ; Dummy for 16-bit channels 
3  2 20 0  14 0      ; TILT
4  0  0 0   0 0      ; Dummy for 16-bit channels 
5  2 40 0  81 0      ; COLOR SPIN
6  2 40 0  38 0      ; COLOR WHEEL
7  2 40 0  49 0      ; LITHO SPIN
8  2 40 0  36 0      ; LITHO
9  2 20 0 101 0      ; LITHO ROT
10 0  0 0   0 0      ; Dummy for 16-bit channels
11 2 40 0  51 0      ; EFFECTS
12 2 40 0 106 0      ; EFFECTS SPEED
13 2  0 0  12 0      ; FOCUS
14 2 40 0  24 0      ; SHUTTER
15 1  0 0   0 0      ; DIMMER
16 2  0 0  25 0      ; M.SPEED
17 2 40 0 107 0      ; MACROS
18 2 40 0  52 0      ; CONTROL
;| |  | |   | |
;| |  | |   | |__ Spare (always 0 for now)
;| |  | |   |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information
; No unused lines allowed between keyword 'WSTART' and last DMX definition
WSTART
6 ffff 8080 3  13 1  5  0 1  0  1  0  0  0  0  0  ; 1. PAN
6 ffff 8080 3  14 1  6  0 1  2  3  0  0  0  0  0  ; 2. TILT
8 ffff    0 1  81 0  1  0 1  4  5  0  0  0  0  0  ; 3. COLOR SPIN
8 ffff    0 1  38 0  3  0 1  5  6  0  0  0  0  0  ; 4. COLOR WHEEL
8 ffff    0 1  49 0 17  0 1  6  7  0  0  0  0  0  ; 5. GOBO SPIN
8 ffff    0 1  36 0  4  0 1  7  8  0  0  0  0  0  ; 6. GOBO
8 ffff 8080 1 101 0  2  0 1  8  9  0  0  0  0  0  ; 7. GOBO ROT
8 ffff    0 1  51 0 25  0 1 10 11  0  0  0  0  0  ; 8. EFFECTS
8 ffff 8080 1 106 0 26  0 1 11 12  0  0  0  0  0  ; 9. EFFECTS SPEED
8 ffff ffff 1  12 0 31  0 1 12 13  0  0  0  0  0  ; 10. FOCUS
8 ffff ffff 1  24 0  7  0 1 13 14  0  0  0  0  0  ; 11. SHUTTER
8 ffff ffff 4   0 0  8  0 1 14 15  0  0  0  0  0  ; 12. DIMMER
8 ffff    0 1  25 0 42  0 1 15 16  0  0  0  0  0  ; 13. M.SPEED
8 ffff    0 1 107 0 47  0 1 16 17  0  0  0  0  0  ; 14. MACROS
8 ffff    0 1  52 0 41  0 1 17 18  0  0  0  0  0  ; 15. CONTROL
;|   |    | |   | |  |  | |  |  |  |  |  |  |  |__ List of Table channels as 
;|   |    | |   | |  |  | |  |  |_______________ line numbers from DMX def.
;|   |    | |   | |  |  | |  |                   0 means unused channel
;|   |    | |   | |  |  | |  |__ DMX line (minus 1) pertainig to this wheel
;|   |    | |   | |  |  | |__ Number of chanels under control OR Table width
;|   |    | |   | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |   | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |   | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |   |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;	eg. for 8 bit channels it is 8, for 12 bit channels it is 4
; 
;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between
;--------------------------------------------------------------------


MACRO "HOME" 1  14  18
28   0  41
 1   0   0
MEND

MACRO "LAMP ON" 2  14  18
28  0  51
 1  0   0
MEND

MACRO "LAMP OFF" 3  14  18
28  0  61
 1  0   0
MEND

MACRO "SHUTDOWN" 4  14  18
28  0  81
 1  0   0
MEND
