#ifndef _SHOWDAEMON_h
#define _SHOWDAEMON_h

enum show_commands {
	SHOW_FUNC_EFFECT_START = 1,
	SHOW_FUNC_EFFECT_END,
	SHOW_FUNC_BARTRIG_START,
	SHOW_FUNC_BARTRIG_END,
	SHOW_FUNC_TS_START,
	SHOW_FUNC_TS_END,
	SHOW_FUNC_RESET,
	SHOW_FUNC_FADE = 10,
	SHOW_FUNC_BLINK,
	SHOW_FUNC_LOCK,
	SHOW_FUNC_CONTROL
};

#endif
