;-----------------------------------------------------------------------|
; Saggitter Infinity Live 1200         personality for the Diamond II   |
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By    | Description                         |
;------------|-----------|--------|-------------------------------------|
;   1.0      |  10-08-01 | Edward | Created from Pearl                  |
;---------------------------------------------------------------------- |


DEVICE=SgInLive12      ; Device Name (upto 11 chars) must be enclosed in single
DEVICE23=               ; 22 chars after '='
                        ; extra information for softkey prompt lines 2&3
                        ; a total of 22 chars, split into 2 lines of 11

;                                  __ Number of lines of DMX info.
;                                 |   __ Number of lines of wheel info
;                                 |  |
;                                 |  |
;                                 |  |
HSTART  1 18 1b05 176 115 ff 0 1 18 18
;       |  |  |    |   |  |  | |
;       |  |  |    |   |  |  | |__ Line number for flash button DMX info
;       |  |  |    |   |  |  |     from DMX definition (1..x)
;       |  |  |    |   |  |  |__ Button release value
;       |  |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;       |  |  |    |   |__ The TILT arc in Degrees
;       |  |  |    |__ The Pan arc in degrees
;       |  |  |__ Date in PC format (1b05==5/08/93)
;       |  |__ Number of DMX slots used
;       |__ Patch direction (1-backward, 2 forward)




TEXTSTART       ; Upto 21 lines of 28 characters
                            ;
    INFINITY LIVE 1200      ;
       PERSONALITY          ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART              ; DMX Picture
1  1  0 0  0 0      ; DIMMER
2  2 40 0 24 0      ; SHUTTER
3  2  0 0 15 0      ; IRIS
4  2  0 0 43 0      ; ZOOM
5  2 40 0 12 0      ; FOCUS
6  2 40 0 36 0      ; GOBO 1
7  2 40 0 37 0      ; GOBO 2
8  2 40 0 49 0      ; GOBO MODE
9  2 40 0 16 0      ; PRISM
10 2  0 0 91 0      ; PRISM MODE
11 2  0 0 51 0      ; EFFECT
12 2 40 0 38 0      ; COLOR
13 2  0 0  8 0      ; CYAN
14 2  0 0  9 0      ; YELLOW
15 2  0 0  7 0      ; MAGENTA
16 2 40 0 52 0      ; CONTROL
17 2 20 0 13 0      ; PAN
18 2 20 0 14 0      ; TILT
;| |  | |  | |
;| |  | |  | |__ Spare (always 0 for now)
;| |  | |  |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 6=instant, 5=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information

WSTART
8 ffff ffff 4  0 0  8  0  1  0  1  0  0  0  0  0      ; 1. DIMMER
8 ffff 1c1c 1 24 0  2  0  1  1  2  0  0  0  0  0      ; 2. SHUTTER
8 ffff 8080 1 15 0  1  0  1  2  3  0  0  0  0  0      ; 3. IRIS
8 ffff    0 1 43 0  3  0  1  3  4  0  0  0  0  0      ; 4. ZOOM
8 ffff 4040 1 12 0  7  0  1  4  5  0  0  0  0  0      ; 5. FOCUS
8 ffff    0 1 36 0 19  0  1  5  6  0  0  0  0  0      ; 6. GOBO 1
8 ffff    0 1 37 0 20  0  1  6  7  0  0  0  0  0      ; 7. GOBO 2
8 ffff    0 1 49 0 17  0  1  7  8  0  0  0  0  0      ; 8. GOBO MODE
8 ffff    0 1 16 0 27  0  1  8  9  0  0  0  0  0      ; 9. PRISM
8 ffff    0 1 91 0 28  0  1  9 10  0  0  0  0  0      ; 10. PRISM MODE
8 ffff    0 1 51 0 25  0  1 10 11  0  0  0  0  0      ; 11. EFFECT
8 ffff    0 1 38 0  4  0  1 11 12  0  0  0  0  0      ; 12. COLOR
8 ffff ffff 1  8 0  9  0  1 12 13  0  0  0  0  0      ; 13. CYAN
8 ffff ffff 1  9 0 11  0  1 13 14  0  0  0  0  0      ; 14. YELLOW
8 ffff ffff 1  7 0 12  0  1 14 15  0  0  0  0  0      ; 15. MAGENTA
8 ffff    0 1 52 0 41  0  1 15 16  0  0  0  0  0      ; 16. CONTROL
4 ffff 8080 3 13 0  5  0  1 16 17  0  0  0  0  0      ; 17. PAN
4 ffff 8080 3 14 0  6  0  1 17 18  0  0  0  0  0      ; 18. TILT
;|   |    | |  | |  |  |  |  |  |  |  |  |  |  |__ List of Table channels as
;|   |    | |  | |  |  |  |  |  |_______________ line numbers from DMX def.
;|   |    | |  | |  |  |  |  |                  ff or 0 means unused channel
;|   |    | |  | |  |  |  |  |__ DMX line pertainnig to this wheel (-1)
;|   |    | |  | |  |  |  |__ Number of chanels under control (Table width)
;|   |    | |  | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |  | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |  | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |  |__  Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tile, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;    eg. for 8 bit channels it is 8, for 12 bit channels it is 4




;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between



MACRO "RESET UNIT" 1  8
50  80
 1   0
MEND


;--------------------------------------------------------------------



