#!/usr/bin/perl -w

use strict;

# blalba;blabla;blabla
 
while(<>) {
	chomp;
	my @a = split /;/, $_;
	print "INSERT INTO `rdmx`.`tc` (`id`, `show`, `position`, `tags`, `comment`) VALUES (NULL, '1', '".$a[0]."', '".$a[1]."', '".(defined $a[2] ? $a[2] : "")."');\n";

}
