;-----------------------------------------------------------------------|
; Robe Colour Spot 700E AT, Mode 1 v1.2, personality for the Diamond II |
;-----------------------------------------------------------------------|
;   History :-                                                          |
;-----------------------------------------------------------------------|
;   Revision |  Date     |  By       | Description                      |
;------------|-----------|-----------|----------------------------------|
;   1.0      |  27-08-09 | David Hunt| Created                          |
;-----------------------------------------------------------------------|


DEVICE=RO_SP70E1v2      ; Device Name (upto 11 chars) must be enclosed in single
DEVICE23=               ; 22 chars after '='
                        ; extra information for softkey prompt lines 2&3
                        ; a total of 22 chars, split into 2 lines of 11

;                                  __ Number of lines of DMX info.
;                                 |   __ Number of lines of wheel info
;                                 |  |
;                                 |  |
;                                 |  |
HSTART  3 36 1b05 530 280 ff 0 35 36 27
;       |  |  |    |   |  |  | |
;       |  |  |    |   |  |  | |__ Line number for flash button DMX info
;       |  |  |    |   |  |  |     from DMX definition (1..x)
;       |  |  |    |   |  |  |__ Button release value
;       |  |  |    |   |  |__ Button ON value (ff means use swop/add fader)
;       |  |  |    |   |__ The TILT arc in Degrees
;       |  |  |    |__ The Pan arc in degrees
;       |  |  |__ Date in PC format (1b05==5/08/93)
;       |  |__ Number of DMX slots used
;       |__ Patch direction (1-backward, 2 forward)




TEXTSTART       ; Upto 21 lines of 28 characters
                            ;
     Robe Colour Spot       ;
      700E AT Mode 1        ;
       PERSONALITY          ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
                            ;
TEXTEND


;------------------------------------------------------------

; For the Attribute Dictionary refer to file 'dict.per'

;------------------------------------------------------------
; DMX information
; No unused lines allowed between keyword 'DSTART' and last DMX definition

DSTART               ; DMX Picture 
1  2 20 0  13 0     ; Pan
2  0  0 0 123 0     ; Pan Fine
3  2 20 0  14 0     ; Tilt
4  0  0 0 124 0     ; Tilt_Fine
5  2  0 0  58 0     ; Speed P/T
6  2 40 0  52 0     ; Control
7  2  0 0 107 0     ; Macro P/T
8  2  0 0 125 0     ; Speed Macro P/T
9  2 20 0   4 0     ; Colour
10 0  0 0   4 0     ; Colour Low
11 2  0 0   8 0     ; Cyan
12 2  0 0   7 0     ; Magenta
13 2  0 0   9 0     ; Yellow
14 2  0 0 149 0     ; CTO
15 2  0 0 147 0     ; CMY Macro
16 2  0 0  59 0     ; CMY Speed
17 2  0 0  51 0     ; Effect/Animation
18 2  0 0  41 0     ; Effect/Animation Rot
19 2 20 0  36 0     ; Gobo 1
20 0  0 0  36 0     ; Gobo 1 Low
21 2 40 0  37 0     ; Gobo 2
22 2 20 0 154 0     ; Gobo 2 Rot
23 0  0 0 154 0     ; Gobo 2 Rot Low
24 2 40 0  16 0     ; Prism
25 2  0 0  78 0     ; Prism Rot
26 2 20 0  40 0     ; Frost
27 0  0 0  40 0     ; Frost Low
28 2 20 0  15 0     ; Iris
29 0  0 0  15 0     ; Iris Low
30 2 20 0  43 0     ; Zoom
31 0  0 0  43 0     ; Zoom Low
32 2 20 0  12 0     ; Focus
33 0  0 0  12 0     ; Focus Low
34 2  0 0  24 0     ; Shutter
35 1  0 0   0 0     ; Dimmer
36 1  0 0   0 0     ; Dimmer Low
;| |  | |   | |
;| |  | |   | |__ Spare (always 0 for now)
;| |  | |   |__ Attribute name (See list above)
;| |  | |__ Curve (0 means no curve otherwise curve number)
;| |  |__ Flags (7=inverted, 40=instant, 20=16-bit)
;| |__ Channel type (1=HTP, 2=LTP, 0=Dummy(for 16-bit defines)
;|__ DMX offset (1..255, 0 means DIMMER will be patched seperately)


;------------------------------------------------------------
; WHEEL information

WSTART
4 ffff 8080 3  13 1  5  0  1 0  1  0  0  0  0  0      ; 1. Pan
4 ffff 8080 3  14 1  6  0  1 2  3  0  0  0  0  0      ; 2. Tilt
8 ffff    0 1  58 0 42  0  1 4  5  0  0  0  0  0      ; 3. Speed P/T
8 ffff    0 1  52 0 41  0  1 5  6  0  0  0  0  0      ; 4. Control
8 ffff    0 1 107 0 27  0  1 6  7  0  0  0  0  0      ; 5. Macro P/T
8 ffff    0 1 125 0 28  0  1 7  8  0  0  0  0  0      ; 6. Speed Macro P/T
4 ffff    0 1   4 1  9  0  1 8  9  0  0  0  0  0      ; 7. Colour
8 ffff    0 1   8 0 10  0  1 10 11 0  0  0  0  0      ; 8. Cyan
8 ffff    0 1   7 0 11  0  1 11 12 0  0  0  0  0      ; 9. Magenta
8 ffff    0 1   9 0 12  0  1 12 13 0  0  0  0  0      ; 10. Yellow
8 ffff    0 1 149 0 15  0  1 13 14 0  0  0  0  0      ; 11. CTO
8 ffff    0 1  59 0 43  0  1 14 15 0  0  0  0  0      ; 12. CMY Speed
8 ffff    0 1 147 0 44  0  1 15 16 0  0  0  0  0      ; 13. CMY Macro
8 ffff    0 1  51 0 20  0  1 16 17 0  0  0  0  0      ; 14. Effect
8 ffff    0 1  41 0 23  0  1 17 18 0  0  0  0  0      ; 15. Effect Rot
4 ffff    0 1  36 1 17  0  1 18 19 0  0  0  0  0      ; 16. Gogo 1
8 ffff    0 1  37 0 18  0  1 20 21 0  0  0  0  0      ; 17. Gobo 2
4 ffff    0 1 154 1 19  0  1 21 22 0  0  0  0  0      ; 18. Gobo 2 Rot
8 ffff    0 1  16 0 25  0  1 23 24 0  0  0  0  0      ; 19. Prism
8 ffff    0 1  78 0 26  0  1 24 25 0  0  0  0  0      ; 20. Prism Rot
4 ffff    0 1  40 1 35  0  1 25 26 0  0  0  0  0      ; 21. Frost
4 ffff    0 1  15 1 36  0  1 27 28 0  0  0  0  0      ; 22. Iris
4 ffff    0 1  43 1 33  0  1 29 30 0  0  0  0  0      ; 23. Zoom
4 ffff    0 1  12 1 34  0  1 31 32 0  0  0  0  0      ; 24. Focus
8 ffff    0 1  24 0  4  0  1 33 34 0  0  0  0  0      ; 25. Shutter
8 ffff ffff 4   0 0  8  0  1 34 35 0  0  0  0  0      ; 26. Dimmer
8 ffff ffff 4   0 0  7  0  1 35 36 0  0  0  0  0      ; 27. Dimmer Low
;|   |    | |   | |  |  |  |  |  | |__|__|__|__|__ List of Table channels as
;|   |    | |   | |  |  |  |  |  |_______________ line numbers from DMX def.
;|   |    | |   | |  |  |  |  |                   ff or 0 means unused channel
;|   |    | |   | |  |  |  |  |__ DMX line pertainnig to this wheel (-1)
;|   |    | |   | |  |  |  |__ Number of chanels under control (Table width)
;|   |    | |   | |  |  |__ Table type (Attribute number) 0 means NOT a table
;|   |    | |   | |  |__ Wheel number (1..8 on bank1, 9..16 on bank2 et cetera)
;|   |    | |   | |__ 0 for 8 bits, 1 for 16 bits
;|   |    | |   |__ Attribute name from above list (0..MAX)
;|   |    | |__ Wheel type (1-offset, 2-Table, 3-Pan/Tilt, 4-Dimmer)
;|   |    |__ Default value (left shifted as necessary)
;|   |__ AND mask, where more than wheel controls same DMX slot
;|__ Wheel multiplication =16-(bits used)
;    eg. for 8 bit channels it is 8, for 12 bit channels it is 4




;--------------------------------------------------------------------
; TABLES
; Each Table is enclosed by the keywords "TSTART" and "*** TEND ***"
; The legend is 16 chars long
; The correct number of values must be supplied (8-bits) with spaces in
; between

;--------------------------------------------------------------------



