appname: "webui2"
layout: "main"
charset: "UTF-8"
template_toolkit: TT
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
session: "cookie"
session_cookie_key: "kjsdf01234hjf0sdkflj12*&(@*jk"
